src/adapters/mapbox-gl.adapter.ts
Adds some baseline improvements to the performance on the Mapbox GL adapter.
Attempts to follow the guidance provided here: https://docs.mapbox.com/help/troubleshooting/mapbox-gl-js-performance/
* Avoids using filters (not really required and adds a perf overhead)
* Debounce renders
* Reduce number of layers and sources to 3 (points, lines, polygons)
=> fix: improve performance of mapbox gl/maplibre gl adapter

src/adapters/common/base.adapter.ts, src/common.ts, src/modes/circle/circle.spec.ts, src/modes/freehand/freehand.mode.spec.ts, src/modes/greatcircle/great-circle.mode.spec.ts, src/modes/linestring/linestring.mode.spec.ts, src/modes/polygon/polygon.mode.spec.ts, src/modes/rectangle/rectangle.mode.spec.ts, src/modes/select/select.mode.spec.ts, src/modes/select/select.mode.ts
=> fix: ensure that preventDefault is only called when necessary

src/adapters/common/base.adapter.ts, src/common.ts, src/modes/base.mode.ts, src/modes/select/behaviors/drag-coordinate.behavior.spec.ts, src/modes/select/behaviors/drag-coordinate.behavior.ts, src/modes/select/behaviors/drag-feature.behavior.spec.ts, src/modes/select/behaviors/drag-feature.behavior.ts, src/modes/select/select.mode.spec.ts, src/modes/select/select.mode.ts, src/terra-draw.ts
=> fix: resolve several issues with selection

src/adapters/mapbox-gl.adapter.ts, src/modes/base.mode.ts, src/modes/select/behaviors/drag-feature.behavior.ts, src/terra-draw.ts
Resolves #51 
Also removes rogue console.log
=> fix: ensure styling is updated for MapboxGL/MapLibreGL style changes

src/terra-draw.ts
=> fix: ensure terra draw instance is enabled on event callback

src/modes/select/behaviors/drag-feature.behavior.ts
=> fix: handle select mode dragging features out of lat/lng bounds

.npmignore, src/modes/polygon/polygon.mode.ts, src/modes/snapping.behavior.ts
=> Fix first click polygon snapping issue

src/modes/freehand/freehand.mode.ts
=> feat: prevent creating points around closing point

guides/GETTING_STARTED.md
=> chore: document how to use terra draw with a script tag

package-lock.json, package.json
I ran the command `npm install --save-dev typescript@5.2.2` , and then `npm run build`. The build did not give any error's.
Just Check the picture once and then if it's okay merge the PR :)
=> TypeScript@5.0.3 to TypeScript@5.2.2

src/adapters/common/base.adapter.ts
=> fix: change default minPixelDragDistanceSelecting to 1

src/adapters/google-maps.adapter.spec.ts, src/adapters/google-maps.adapter.ts
=> fix: ensure that google maps cursor changing works across different language settings

src/adapters/google-maps.adapter.spec.ts, src/adapters/google-maps.adapter.ts
=> fix: ensure cursors are respected properly for the Google Maps API

src/adapters/mapbox-gl.adapter.ts
=> fix: ensure that rendered layers are removed properly on clear for MapboxGL/MapLibreGL

.github/workflows/ci.yml
=> chore: add linting as a step on CI

.github/workflows/ci.yml
=> chore: cache playwright browser

e2e/public/index.html, e2e/src/index.ts, e2e/tests/leaflet.spec.ts, e2e/tests/setup.ts
=> test: add basic tests for Rectangle, Circle, Great Circle and Select modes

src/modes/circle/circle.mode.spec.ts, src/modes/circle/circle.mode.ts
=> fix: ensure circle mode works on touch devices

.github/pull_request_template.md
Resolves #120 
The aim here is to improve the quality of Pull Request submissions and ensure that issues are created in advance of PR's being raise to foster open discussion.
=> docs: add GitHub pull request template for the repository

guides/2.STORE.md, guides/4.MODES.md
Makes two small changes: 
* Adds guidance around changing modes
* Replaces non existing 'setFeatures' method to 'addFeatures' in the localStorage example
https://github.com/JamesLMilner/terra-draw/issues/172
=> docs: improve documentation around changing mode

guides/3.ADAPTERS.md
Remove references to lib where not required in the adapters guide
#195
=> docs: remove lib passed to various adapters in the adapters guide

README.md
Adds a contact email address for the project
No issue
=> chore: add contact email

src/modes/circle/circle.mode.spec.ts, src/modes/circle/circle.mode.ts
Adds a minimum circle radius configuration with a very small default (currently the default width of an initially created circle) and also stores the current radius in the circle.
#222 
#221
=> feat: for circle mode provide minimum radius config and store radius in circle properties

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature-request.md
Adds a Feature Request template
=> docs: update issue templates, include Feature request

development/src/index.ts, e2e/src/index.ts, e2e/tests/leaflet.spec.ts, guides/4.MODES.md, src/geometry/project/web-mercator.spec.ts, src/geometry/project/web-mercator.ts, src/modes/select/behaviors/drag-coordinate-resize.behavior.spec.ts, src/modes/select/behaviors/drag-coordinate-resize.behavior.ts, src/modes/select/select.mode.spec.ts, src/modes/select/select.mode.ts
This PR completely refactors resizable:
* A lot of the functionality was half baked and not working as well as it could be
* Removes all geodesic options, _for now_ to focus on Web Mercator projection resizing 
* Removes the fixed options, _for now_ to focus on non fixed options
* Dragging should better follow the mouse cursor
* Removes limitations on closeness of points
* Fixes various bugs with the resizing
=> Refactor resizable

guides/4.MODES.md, src/modes/select/behaviors/drag-coordinate-resize.behavior.spec.ts, src/modes/select/behaviors/drag-coordinate-resize.behavior.ts
* adds center-fixed-web-mercator mode
* adds opposite-fixed-web-mercator mode
* adds basic unit tests around it
No issue
=> feat: add additional web-mercator options for resizeable

.devcontainer/devcontainer.json, .github/workflows/alpha-release.yml, .github/workflows/ci.yml, guides/7.DEVELOPMENT.md, package-lock.json
* Change usage of Node to version 20
* npm audit fix to remove alerts
#234
=> chore: move to using Node 20 and npm 10 for development

development/src/index.ts, guides/4.MODES.md, src/geometry/measure/area.ts, src/modes/select/behaviors/drag-coordinate-resize.behavior.ts, src/modes/select/behaviors/drag-coordinate.behavior.ts, src/modes/select/behaviors/drag-feature.behavior.ts, src/modes/select/behaviors/rotate-feature.behavior.ts, src/modes/select/behaviors/scale-feature.behavior.ts, src/modes/select/select.mode.ts, src/terra-draw.ts, src/validations/max-size.validation.spec.ts, src/validations/max-size.validation.ts, src/validations/min-size.validation.spec.ts, src/validations/min-size.validation.ts
Provide a method for validating edits in select mode
#239
=> feat: allow custom validations on select mode

src/validations/max-size.validation.ts
=> rename minSize to maxSize in ValidateMaxAreaSquareMeters.

package.json
This change is slightly speculative and I'm not sure how many bundlers still reflect "sideEffects", but at least Webpack and Vite seem too. 
Here's some context on the property: https://sgom.es/posts/2020-06-15-everything-you-never-wanted-to-know-about-side-effects/
=> chore: add sideEffects: false to package.json

.github/ISSUE_TEMPLATE/chore.md
Tiny PR to automatically prefix chore issues with [Chore] 
No issue
=> chore: add [Chore] automatically to chore issues created from template

scripts/next-beta-version.ts
* Fixes release script so that beta release can be released correctly (rename next-alpha-version.ts -> next-beta-version.ts)
=> chore: fix beta release script to be named correct

.github/workflows/beta-release-increment.yml, .github/workflows/beta-release-v1.yml
* Previous beta release scripts were not quite write in there usage of `release`-as and `prerelease` flags. This PR aims to resolve those.
No issue
=> chore: rewrite beta release script

package.json
* npm scripts were missing for beta release, this resolves that
No issue
=> chore: update npm scripts to be correct for beta release

.github/workflows/beta-release-v1.yml
The check for changelog is well intentioned but in the major case breaks, so we will remove it in this script for now.
No issue
=> chore: remove check for changelog as layout is markdown different for major release

guides/7.DEVELOPMENT.md
Improve development guide on how to create a watching build.
#283
=> docs: improve guide to create a watching build

guides/3.ADAPTERS.md
Add openlayers example to the adapters guide.
#93
=> docs: add OpenLayers example to adapters guide

guides/1.GETTING_STARTED.md, guides/4.MODES.md
Added information on which modes are available for small screen devices
https://github.com/JamesLMilner/terra-draw/issues/107
=> docs: update Getting Started and Modes guide to say which modes are available in mobile mode

README.md, package-lock.json, package.json, src/adapters/openlayers.adapter.ts
Bumps supported OpenLayers version to 10, speculatively fixing the drawing issue on Windows
https://github.com/JamesLMilner/terra-draw/issues/302
=> chore: bump supported version of OpenLayersAdapter to version 10

.github/FUNDING.yml
Adds sponsorship button for Terra Draw
No issue
=> docs: create FUNDING.yml for to add sponsorship button to repository

src/geometry/midpoint-coordinate.ts, src/modes/select/behaviors/rotate-feature.behavior.ts
Removes logs that got in by accident 
No issue
=> fix: remove unnecessary logs from the codebase

scripts/changelog-valid.ts
Updates release script check to log changes and version for easier debugging
No issue
=> chore: log out changes in release check script

scripts/changelog-valid.ts
This should fix the changelog check script to work for beta releases
No issue
=> chore: fix release script to ensure that beta releases pass changelog check

guides/CODE_OF_CONDUCT.md
Updates the email for the code of conduct 
No issue
=> docs: update CODE_OF_CONDUCT.md email 

guides/CODE_OF_CONDUCT.md
Updates the email for the code of conduct
No issue
=> docs: update CODE_OF_CONDUCT.md email

guides/1.GETTING_STARTED.md, guides/2.STORE.md, guides/3.ADAPTERS.md, guides/4.MODES.md, guides/5.STYLING.md, guides/6.EVENTS.md, guides/7.DEVELOPMENT.md, guides/8.EXAMPLES.md
Provide a list of examples that people can use as a point of reference
No issue
=> docs: add examples page to the guides

src/adapters/leaflet.adapter.spec.ts, src/adapters/leaflet.adapter.ts
Adds unit tests for the Leaflet adapter (TerraDrawLeafletAdapter)
No issue
=> test: add Leaflet adapter unit tests

src/adapters/mapbox-gl.adapter.spec.ts, src/adapters/mapbox-gl.adapter.ts
Adds unit tests for the Mapbox adapter (TerraDrawMapboxGLAdapter)
https://github.com/JamesLMilner/terra-draw/issues/89
=> test: add Mapbox adapter unit tests

src/adapters/mapbox-gl.adapter.ts
Slightly simplifies the render function for the MapboxGL Adapter
No issue
=> fix: simplify the render function in TerraDrawMapboxAdapter

src/geometry/centroid.ts, src/geometry/measure/area.ts, src/geometry/measure/bearing.ts, src/geometry/measure/destination.ts, src/geometry/measure/rhumb-bearing.ts, src/geometry/measure/rhumb-destination.ts, src/geometry/measure/rhumb-distance.ts, src/geometry/measure/slice-along.ts, src/geometry/midpoint-coordinate.ts, src/geometry/shape/create-circle.ts, src/geometry/transform/rotate.ts, src/geometry/transform/scale.ts
Adds some clarification on where certain modules come from and tries to make it more consistent
No issue
=> chore: clarify turf.js adapted code

.github/workflows/ci.yml, package-lock.json, package.json, src/common.ts, src/store/store.ts, src/test/mock-unproject.ts
Adds knip to the CI pipeline. Knip checks for unused exports from the project, helping detect unused codes and types.
No issue
=> chore: add unused code export check with knip

development/src/index.ts, guides/3.ADAPTERS.md, src/adapters/openlayers.adapter.spec.ts, src/adapters/openlayers.adapter.ts
Adds unit tests for the OpenLayers adapter
#90
=> test: add OpenLayers adapter unit tests

src/store/store.ts
=> fix: improved error message for store feature validation

development/public/index.html, development/src/config.ts, development/src/index.ts, e2e/public/index.html, e2e/src/index.ts, e2e/tests/leaflet.spec.ts, e2e/tests/setup.ts, guides/5.STYLING.md, src/modes/sensor/sensor.mode.spec.ts, src/modes/sensor/sensor.mode.ts, src/terra-draw.ts
* Adds in TerraDrawSensorMode
* Adds unit tests with 80%+ unit test coverage
* Adds E2E tests for the new mode
#326
=> feat: add in new TerraDrawSensorMode for drawing sensors, complete with tests 

src/geometry/web-mercator-centroid.spec.ts
Fixes failures with floating point precision in web-mercator-centroid.spec.ts
No ticket
=> test: fix floating point issues on web-mercator-centroid.spec.ts

eslint.config.js, package-lock.json, package.json, src/adapters/arcgis-maps-sdk.adapter.ts, src/adapters/google-maps.adapter.ts, src/adapters/leaflet.adapter.ts, src/adapters/mapbox-gl.adapter.ts, src/adapters/openlayers.adapter.ts, src/modes/angled-rectangle/angled-rectangle.mode.ts, src/modes/base.mode.ts, src/modes/circle/circle.mode.ts, src/modes/freehand/freehand.mode.ts, src/modes/linestring/linestring.mode.ts, src/modes/rectangle/rectangle.mode.ts, src/modes/sector/sector.mode.ts, src/modes/static/static.mode.ts, src/terra-draw.extensions.spec.ts
Upgrades from eslint v8 to eslint v9
#374
=> chore: upgrade prettier to version 9

guides/4.MODES.md
=> docs: fixed documentation error for validate function

eslint.config.js, src/modes/linestring/linestring.mode.ts
This will help ensure console.log/warn/error etc do not end up in the codebase by erroring on CI on the lint step if they are present
No issue
=> chore: lint error in CI if console is called

.github/workflows/release-terra-draw.yml
Adds a script for full releases of the `terra-draw` package
No issue
=> chore(terra-draw): add an action for full release of terra-draw

.github/workflows/terra-draw-arcgis-adapter-dry-run-release.yml, .github/workflows/terra-draw-arcgis-adapter-release.yml, .github/workflows/terra-draw-google-maps-adapter-dry-run-release.yml, .github/workflows/terra-draw-google-maps-adapter-release.yml, .github/workflows/terra-draw-leaflet-adapter-dry-run-release.yml, .github/workflows/terra-draw-leaflet-adapter-release.yml, .github/workflows/terra-draw-mapbox-gl-adapter-dry-run-release.yml, .github/workflows/terra-draw-mapbox-gl-adapter-release.yml, .github/workflows/terra-draw-maplibre-gl-adapter-dry-run-release.yml, .github/workflows/terra-draw-maplibre-gl-adapter-release.yml, .github/workflows/terra-draw-openlayers-adapter-dry-run-release.yml, .github/workflows/terra-draw-openlayers-adapter-release.yml, .github/workflows/terra-draw-release-dry-run.yml, .github/workflows/terra-draw-release.yml
Adds release actions for all adapters
#259
=> chore(terra-draw): add release actions for all adapters

.github/workflows/terra-draw-google-maps-adapter-dry-run-release.yml, .github/workflows/terra-draw-google-maps-adapter-release.yml, packages/terra-draw-arcgis-adapter/.versionrc.cjs, packages/terra-draw-google-maps-adapter/.versionrc.cjs, packages/terra-draw-leaflet-adapter/.versionrc.cjs, packages/terra-draw-mapbox-gl-adapter/.versionrc.cjs, packages/terra-draw-maplibre-gl-adapter/.versionrc.cjs, packages/terra-draw-openlayers-adapter/.versionrc.cjs
Makes some small fixes to the release actions
#259
=> chore(terra-draw): fix small issues with releasing actions adapters

packages/terra-draw-arcgis-adapter/package.json, packages/terra-draw-google-maps-adapter/package.json, packages/terra-draw-leaflet-adapter/package.json, packages/terra-draw-mapbox-gl-adapter/package.json, packages/terra-draw-maplibre-gl-adapter/package.json, packages/terra-draw-openlayers-adapter/package.json, packages/terra-draw/package.json
Ensures that releases are tagged correctly
#259
=> chore(terra-draw): fix tagging when releasing via actions

release.js
Makes the release message a little more meaningful
#259
=> chore(terra-draw): improve the release commit message when releasing

README.md
Updates the README to have the accurate supported versions
No issue
=> chore(terra-draw): update javascript versions of supported libraries to be accurate in README

.github/workflows/terra-draw-maplibre-gl-adapter-release.yml, packages/terra-draw-maplibre-gl-adapter/README.md
PR aims to add a better documented README to the `terra-draw-maplibre-gl-adapter` npm package.
No issue
=> fix(terra-draw-maplibre-gl-adapter): ensure the README has correct links on npm

.github/workflows/commit-lint-prs.yml
Ensure the correct syntax for the GitHub action, also avoid inline expressions in the action.
No issue
=> chore(terra-draw): fix issue with commit-lint-prs.yml GitHub action

guides/7.DEVELOPMENT.md
- **its** testing framework...
see:
https://www.merriam-webster.com/dictionary/it's
=> docs(terra-draw): 7.DEVELOPMENT.md wrong apostrophe

guides/4.MODES.md
- **its** name...
- **per**forming the...
- provis**io**nal
- su**pp**orted
- Re**ct**angle
- De**sel**ect
spelling
=> docs(terra-draw): fix spelling and grammar issues in 4.MODES.md

.github/workflows/terra-draw-release.yml, packages/terra-draw/README.md
We were going to copy in the README from the main repository, but this wont' actually work very well due to relative paths. This also allows us to be more specific in what we chose to put in there and publish to npm.
No issue
=> chore(terra-draw): use a custom README for the terra-draw package

guides/2.STORE.md, packages/terra-draw/src/store/store.ts, packages/terra-draw/src/terra-draw.spec.ts, packages/terra-draw/src/terra-draw.ts
Provides a convenience method for easily retrieve a copy of a feature from the store
https://github.com/JamesLMilner/terra-draw/issues/470
=> feat(terra-draw): add getSnapshotFeature method to allow fetching single features easily

guides/2.STORE.md
The existing description for IDs felt a bit unwieldly, and simplifying it slightly seems to make it flow better without any information loss.
No issue yet, and creating one seems like overkill in this particular case?
=> docs(terra-draw): slightly simplified wording about ids

packages/terra-draw-leaflet-adapter/src/terra-draw-leaflet-adapter.ts
This will ensure that style changes when styles are changed programatically via `updateModeOptions`
https://github.com/JamesLMilner/terra-draw/issues/472
=> fix(terra-draw-leaflet-adapter): ensure that the leaflet adapter renders on style change

packages/terra-draw/src/modes/polygon/polygon.mode.ts
Provides a context object that has useful data and methods for handling custom snapping functionality 
No issue
=> feat(terra-draw): provide context object argument to toCustom callback in polygon mode

guides/4.MODES.md
Add a section on updateModeOptions to MODES guide to make it clearer on how to change options after instantiation.
No issue
=> docs(terra-draw): add section on updateModeOptions to MODES guide

.github/workflows/terra-draw-arcgis-adapter-release.yml, .github/workflows/terra-draw-google-maps-adapter-release.yml, .github/workflows/terra-draw-leaflet-adapter-release.yml, .github/workflows/terra-draw-mapbox-gl-adapter-release.yml, .github/workflows/terra-draw-maplibre-gl-adapter-release.yml, .github/workflows/terra-draw-openlayers-adapter-release.yml, .github/workflows/terra-draw-release.yml, packages/development/package.json, packages/e2e/package.json
Also add package.json files on change to package-lock.json file. This will help keep CI green.
No issue
=> chore(terra-draw): ensure package.json files are added on automated updates in CI

packages/development/src/index.ts, packages/terra-draw-maplibre-gl-adapter/src/terra-draw-maplibre-gl-adapter.spec.ts, packages/terra-draw-maplibre-gl-adapter/src/terra-draw-maplibre-gl-adapter.ts
This PR allows handling of layered points by creating a separate layer for points that sit under the main points layer
No issue
=> fix(terra-draw-maplibre-gl-adapter): better handle zindexes to support layered points

packages/terra-draw-maplibre-gl-adapter/src/terra-draw-maplibre-gl-adapter.ts
- Control the order with renderBelowLayerId
- Remove layer reordering in render and register which was unnecessary
- Ensure layers are created in the correct order to begin with
Partially resolves https://github.com/JamesLMilner/terra-draw/issues/394
=> feat(terra-draw-maplibre-gl-adapter): add renderBelowLayerId option to control render order

packages/terra-draw/README.md
Fixed a broken link in the package description of terra-draw:
https://www.npmjs.com/package/terra-draw
=> docs(terra-draw): fix package name of terra-draw-maplibre-gl-adapter in README

guides/4.MODES.md
I found a link in MODES.md has expired
=> docs(terra-draw): update a link in 4.MODES.md

packages/terra-draw/src/modes/select/select.mode.ts
Selection points were not being cleaned up properly on delete key up. This PR resolves that by cleaning them up correctly.
https://github.com/JamesLMilner/terra-draw/issues/564
=> fix(terra-draw): ensure coordinate points are cleaned up after delete

packages/terra-draw-mapbox-gl-adapter/src/terra-draw-mapbox-gl-adapter.ts
I applied the same changes of https://github.com/JamesLMilner/terra-draw/pull/578 for mapbox adapter
#577
=> feat(terra-draw-mapbox-gl-adapter): add prefixId argument in constructor to change layer prefix

.github/workflows/ci.yml, guides/7.DEVELOPMENT.md, package-lock.json, packages/storybook/README.md, packages/storybook/package.json, packages/storybook/src/common/config.ts, packages/storybook/src/common/setup.ts, packages/storybook/src/common/stories.ts, packages/storybook/src/introduction.stories.ts, packages/storybook/src/stories/arcgis/ArcGIS.stories.ts, packages/storybook/src/stories/arcgis/setup.ts, packages/storybook/src/stories/google/Google.stories.ts, packages/storybook/src/stories/google/setup.ts, packages/storybook/src/stories/leaflet/Leaflet.stories.ts, packages/storybook/src/stories/leaflet/setup.ts, packages/storybook/src/stories/mapbox/Mapbox.stories.ts, packages/storybook/src/stories/mapbox/setup.ts, packages/storybook/src/stories/maplibre/MapLibre.stories.ts, packages/storybook/src/stories/maplibre/setup.ts, packages/storybook/src/stories/openlayers/OpenLayers.stories.ts, packages/storybook/src/stories/openlayers/setup.ts
This PR enables smoke tests for Storybook, ensuring all stories can render without error. This helps ensure the integrity of both the Storybook itself and Terra Draw more broadly.
https://github.com/JamesLMilner/terra-draw/issues/606
=> chore(terra-draw): add smoke tests for Storybook examples

README.md
- Uses shields.io consistently for non CI related badges
- Add sponsors badge
No issue
=> chore(terra-draw): update badges in the README, add sponsors link
