JamesLMilner/terra-draw

guides/GETTING_STARTED.md, src/common.ts, src/modes/base.mode.ts, src/modes/circle/circle.mode.ts, src/modes/freehand/freehand.mode.ts, src/modes/greatcircle/great-circle.mode.ts, src/modes/linestring/linestring.mode.spec.ts, src/modes/linestring/linestring.mode.ts, src/modes/point/point.mode.spec.ts, src/modes/point/point.mode.ts, src/modes/polygon/polygon.mode.spec.ts, src/modes/polygon/polygon.mode.ts, src/modes/rectangle/rectangle.mode.spec.ts, src/modes/rectangle/rectangle.mode.ts, src/modes/render/render.mode.spec.ts, src/modes/render/render.mode.ts, src/modes/select/select.mode.spec.ts, src/modes/select/select.mode.ts
This PR resolves #59 - it allows the ability to style any feature in a given mode using styling functions. This means that features can be styled on other values such as a cached random colour based on the feature id. However this could be extended in the future to be based on properties or be based on other external data if required.
A small example is provided in the getting started guide to help show to to make that happen.
=> feat: add function based styling for all modes and styles

.gitignore, development/index.html, development/src/index.ts, package-lock.json, package.json, src/adapters/arcgis-maps-sdk.adapter.spec.ts, src/adapters/arcgis-maps-sdk.adapter.ts
Hope you got back well from FOSS4G! ;)
As discussed at FOSS4G, I tried to whip up and Esri ArcGIS Maps SDK adapter.
The functionality is working, so if you want to glance over it, feel free to add suggestions. Couple of things to note:
* I am using a single [GraphicsLayer](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-GraphicsLayer.html) instead of a [GeoJSONLayer](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-GeoJSONLayer.html). The advantage being that it's less abstraction and we don't have to maintain several layers and split the features accordingly (since the GeoJSONLayer only accepts features of the same type along [some other limitations](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-GeoJSONLayer.ht …
=> feat: add Esri ArcGIS Maps SDK adapter

src/adapters/common/base.adapter.ts, src/common.ts, src/modes/circle/circle.mode.ts, src/modes/freehand/freehand.mode.ts, src/modes/greatcircle/great-circle.mode.ts, src/modes/linestring/linestring.mode.ts, src/modes/point/point.mode.ts, src/modes/polygon/polygon.mode.ts, src/modes/rectangle/rectangle.mode.ts, src/modes/select/select.mode.spec.ts, src/modes/select/select.mode.ts
Resolves #49 
Allows cursors to be configured via a config option in each mode
Changes default cursor for dragging features/coordinates to the move icon rather than grab
=> feat: allow cursors to be configured for built in modes

src/modes/select/behaviors/drag-coordinate.behavior.spec.ts, src/modes/select/behaviors/drag-coordinate.behavior.ts, src/modes/select/select.mode.ts
The constructor for TerraDrawSelectMode may now contain an additional field called "selfIntersectable" that, when toggled true, will allow Polygons or LineStrings to become self-intersecting through edits in select mode. When the selfIntersectable field is omitted from teh TerraDrawSelectMode constructor, the default behavior is to prohibit self-intersections from occurring in select mode.
I added an additional parameter in the drag() function of drag-coordinate.behavior.ts to specify whether or not geometry updates containing self-intersections should be saved to the store. If self-intersections are prohibited and the registered mouse event would cause a self-intersection, the attempted geometry changes will not save to the store, and the function will return false. I also wrote new …
=> Preventing Polygon Self-Intersection with Select Mode

guides/COMMON_PATTERNS.md, src/common.ts, src/geometry/shape/create-bbox.spec.ts, src/geometry/shape/create-bbox.ts, src/modes/click-bounding-box.behavior.ts, src/modes/select/behaviors/drag-feature.behavior.spec.ts, src/modes/select/behaviors/drag-feature.behavior.ts, src/modes/select/behaviors/feature-at-pointer-event.behavior.spec.ts, src/modes/select/behaviors/feature-at-pointer-event.behavior.ts, src/modes/select/select.mode.ts, src/terra-draw.ts
Adds two methods to the main Terra Draw API:
`.getFeaturesAtLngLat`
Allows for retrieval of features at a given latitude and longitude
and:
`.getFeaturesAtPointerEvent`
Allows for retrieval of features at a given mouse or pointer event
Resolves #74
=> feat: add getFeaturesAtLngLat and getFeaturesAtPointerEvent methods

src/adapters/common/base.adapter.ts, src/common.ts, src/geometry/shape/create-bbox.spec.ts, src/modes/base.mode.ts, src/modes/select/select.mode.spec.ts, src/modes/select/select.mode.ts
Creates a new state called `selecting` and then allows for setting custom threshold for micro drags, as per for drawing and regular interactions around the map.
Aims to resolve #77
=> feat: allow custom limits of microdrags whilst selecting

src/modes/select/select.mode.spec.ts, src/modes/select/select.mode.ts
Resolves #80 
`onFinished` event should now be fired at the end of dragging a feature or coordinate in Select mode. Includes unit tests to help ensure it works.
=> fix: fire an onFinish event when finished dragging a coordinate or feature

package-lock.json, package.json
Resolves #78 - `ts-node` shouldn't have been listed as a dependency and instead a devDependency
=> chore: remove ts-node from dependencies list

development/src/index.ts, src/adapters/google-maps.adapter.ts
Fixes #76, by using the built in fromContainerPixelToLatLng / fromLatLngToContainerPixel.
=> fix: corrected project/unproject when tilting/rotating a google vector map

README.md, guides/DEVELOPMENT.md, package-lock.json
=> Update the DEVELOPMENT guide to reference Node 18 LTS and npm 9

package-lock.json, package.json, src/adapters/google-maps.adapter.spec.ts, src/adapters/google-maps.adapter.ts
Add more tests for the Google Maps adapter. With these changes, coverage by statements and by lines are now just over 80% for the Google Maps adapter.
Closes #88 
Note that these changes add [JSDOM](https://github.com/jsdom/jsdom) to enable DOM emulation for the tests. This was the [simplest](https://github.com/JamesLMilner/terra-draw/issues/88#issuecomment-1745749984) way to get the tests up and running for this adapter. For now I've only enabled the JSDOM environment for the Google Maps adapter (via the `@jest-environment` [directive in the docblock](https://jestjs.io/docs/configuration#testenvironmentoptions-object) ), so the environment remains the same (still [`node`](https://github.com/JamesLMilner/terra-draw/blob/main/jest.config.ts#L14)) for the other modules.
In addition to …
=> test: improve test coverage of Google Maps adapter

src/adapters/google-maps.adapter.spec.ts, src/adapters/google-maps.adapter.ts, src/test/mock-callbacks.ts
This PR proposes a few smaller changes to internal organization and conventions used in the Google Maps Adapter.
The main changes, which split out set up of the event listeners to their own method, invoked in the constructor, come from [this previous comment](https://github.com/JamesLMilner/terra-draw/pull/98#discussion_r1359947432).
The other two are some small things that occurred to me while writing the tests:
- The internal property for tracking what was rendered was tracking the Feature IDs, but was named `renderedFeatures`. This briefly lead to confusion when comparing it to [`TerraDrawChanges`](https://github.com/JamesLMilner/terra-draw/blob/main/src/common.ts#L117), which uses [`deletedIds`](https://github.com/JamesLMilner/terra-draw/blob/main/src/common.ts#L121) to indicate the …
=> refactor: move Adapter event listener init and small convention improvements

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/post-create.sh
For `Hacktoberfest`, I have been adding `GitHub Codespaces` / `VS Code Remote Containers` configuration for OSS projects to make it easier for contributors to the project to get up and running with the correct developer setup. Including the appropriate configuration for a project allows contributors to work entirely within a web browser via `GH Codespaces`, or inside of fully, and correctly configured containers on their own computer with `VS Code Remote Containers` (both of these use the same configuration, as `GH Codespaces` leverages the `Remote Containers` features under the hood).
For the `terra-draw ` project, this configuration includes the following:
- Preinstalled `Node LTS`
- Preinstalled `ESLint`,  `Prettier`, and `DotENV` extensions
- Automation of the `npm install` when the …
=> feat(devcontainers): add the ability to use GitHub Codespaces and VS Code remote containers

development/src/index.ts, src/terra-draw.ts
The Esri ArcGIS Maps SDK adapter added in #58 is not exported. This PR adds the export and updates the development/ app to import from there.
=> fix: add TerraDrawArcGISMapsSDKAdapter to terra-draw exports

.gitignore, development/public/index.html, development/src/index.ts
This PR includes the following improvements to the development/ app:
- Add labels to identify each mapping library
- Use OSM tiles for MapLibre
- Removed unused accessToken parameter for initMapLibre()
- Load MapLibre CSS
- Adjusted some map zooms so they all match
- As a backup, load Google Maps using empty API key none provided (map loads, but displays warning)
- As a backup, load MapBox GL using an invalid token and use OSM tiles if no access token provided (loads map, but console errors)
=> feat: improved development mapping library integrations

src/adapters/common/base.adapter.ts, src/adapters/google-maps.adapter.ts
This PR aims to resolve #129 
It makes getMapEventElement take an argument so we can apply different types of events handlers to different elements if required. 
Here we apply the keyboard handler to the document which seems odd but this does seems to be the default focus when you select the Google Map, so perhaps not so odd.
Should allow keyboard events to work for Google Maps again.
=> fix: ensure keyboard events are capture for the Google Maps API

src/modes/base.mode.ts, src/modes/circle/circle.spec.ts, src/modes/freehand/freehand.mode.spec.ts, src/modes/greatcircle/great-circle.mode.spec.ts, src/modes/linestring/linestring.mode.spec.ts, src/modes/point/point.mode.spec.ts, src/modes/polygon/polygon.mode.spec.ts, src/modes/rectangle/rectangle.mode.spec.ts, src/modes/render/render.mode.spec.ts
Fixes hard coding of the coordinate precision and then the unit tests to run the register function first before attempting to validate.
=> fix: ensure coordinate precision is set via the config to the adapter

.github/workflows/ci.yml, .gitignore, e2e/README.md, e2e/package-lock.json, e2e/package.json, e2e/playwright.config.ts, e2e/public/index.html, e2e/src/index.ts, e2e/tests/leaflet.spec.ts, e2e/tests/setup.ts, e2e/webpack.config.js, jest.config.ts, jest.nocheck.config.ts
Experiments with adding basic E2E tests to the project using Playwright. At the moment the test suite runs against the Leaflet adapter as this updates the DOM using SVG which makes it easier to assert on the outcomes.
=> chore: add e2e testing suite using Playwright

e2e/README.md
This PR just adds a little more detail to the E2E tests to make the README slightly more useful.
=> chore: add clarification around E2E README

guides/3.MODES.md
This aims to provide better documentation on select mode and on how to handle getting selecting features via events. 
Resolves #131
=> docs: add better documentation on selecting features

guides/1.GETTING_STARTED.md, guides/2.STORE.md, guides/3.ADAPTERS.md, guides/4.MODES.md, guides/5.STYLING.md, guides/6.EVENTS.md, guides/7.DEVELOPMENT.md
Adds a store guide providing information on how to work with getting data in and out of Terra Draw.
=> docs: add store documentation to the guides

.github/workflows/alpha-release.yml, package-lock.json, package.json, scripts/changelog-valid.ts, tsconfig.json
Aims to help with ensuring releases are done correctly when triggered from a GitHub action. 
* Aims to ensure that a release can only be done if there are commits to be released
* There appears to be an issue with generating the correct Changelog, so this adds a check to ensure that it is correctly formatted
=> chore: add assurances to release script to prevent invalid changelog

.github/workflows/alpha-release.yml
I think this should resolve the issue of the changelog being populated incorrectly. Let's see!
=> fix: ensure full commit history is fetched for releasing so changelog is populated correctly

.github/workflows/alpha-release.yml
Ensures that push can happen before attempting to push the tags. This avoids situation where tags get push but the main push has failed because of credential issues.
=> chore: attempt push to main first before pushing tags incase push to main fails

src/adapters/arcgis-maps-sdk.adapter.ts, src/adapters/common/base.adapter.ts, src/adapters/google-maps.adapter.spec.ts, src/adapters/google-maps.adapter.ts, src/adapters/leaflet.adapter.spec.ts, src/adapters/leaflet.adapter.ts, src/adapters/mapbox-gl.adapter.spec.ts, src/adapters/mapbox-gl.adapter.ts, src/adapters/maplibre-gl.adapter.spec.ts, src/adapters/maplibre-gl.adapter.ts, src/adapters/openlayers.adapter.spec.ts, src/adapters/openlayers.adapter.ts
This PR should allow for the setting of the base adapter settings in extending adapters. Namely ensuring the ability to configure:
```typescript
coordinatePrecision?: number;
minPixelDragDistanceDrawing?: number;
minPixelDragDistance?: number;
minPixelDragDistanceSelecting?: number;
```
Across all extending adapters (Leaflet, Google Maps, ArcGIS, Mapbox, Maplibre). 
#167
=> fix: ensure that base config parameters can be configured for adapters

guides/3.ADAPTERS.md, src/adapters/google-maps.adapter.spec.ts, src/adapters/google-maps.adapter.ts
1. Aims to clarify the around the necessity for and ID to be set on the map passed to the `TerraDrawGoogleMapAdapter` instance
2. Throw an error if the `id` attribute is not set on the map div
#176
=> docs: clarify the requiremnts for google maps and throw error if element id is not set

guides/2.STORE.md, guides/4.MODES.md, src/adapters/google-maps.adapter.ts, src/adapters/openlayers.adapter.ts, src/common.ts, src/modes/base.mode.ts, src/modes/circle/circle.mode.ts, src/modes/freehand/freehand.mode.ts, src/modes/great-circle-snapping.behavior.ts, src/modes/greatcircle/great-circle.mode.ts, src/modes/linestring/linestring.mode.ts, src/modes/polygon/polygon.mode.ts, src/modes/rectangle/rectangle.mode.ts, src/modes/select/behaviors/drag-coordinate.behavior.ts, src/modes/select/behaviors/drag-feature.behavior.ts, src/modes/select/behaviors/midpoint.behavior.ts, src/modes/select/behaviors/rotate-feature.behavior.ts, src/modes/select/behaviors/scale-feature.behavior.ts, src/modes/select/behaviors/selection-point.behavior.ts, src/modes/select/select.mode.ts, src/modes/snapping.behavior.ts, src/store/spatial-index/spatial-index.ts, src/store/store-feature-validation.ts, src/store/store-validation.spec.ts, src/store/store.spec.ts, src/store/store.ts, src/terra-draw.spec.ts, src/terra-draw.ts
It has historically not been possible to use your own IDs with Terra Draw as they would always be created with UUIDv4. This is generally fine, but there are scenarios were people may want to bring their own id creation strategy along, and not use UUIDv4. This PR allows for that.
#179
=> feat: allow custom id strategies

src/adapters/google-maps.adapter.ts
Fixes the selector in the Google Maps Adapter so the cursor class can be added correctly and cursors are respected.
#181
=> fix: ensure that cursors are respected with the google maps adapter

src/terra-draw.spec.ts
Small improvement the unit test coverage of `terra-draw.ts`. Little and often! Adds:
* .enabled() tests
* .setMode('mode') tests
No issue
=> test: improve test coverage of terra-draw.ts

.github/workflows/ci.yml, development/src/index.ts, e2e/package-lock.json, e2e/package.json, e2e/playwright.config.ts, e2e/public/index.html, e2e/src/index.ts, e2e/tests/leaflet.spec.ts, e2e/tests/setup.ts, e2e/webpack.config.js, guides/4.MODES.md, src/geometry/transform/scale.spec.ts, src/geometry/transform/scale.ts, src/modes/select/behaviors/drag-maintained-shape.behavior.spec.ts, src/modes/select/behaviors/drag-maintained-shape.behavior.ts, src/modes/select/behaviors/scale-feature.behavior.ts, src/modes/select/select.mode.spec.ts, src/modes/select/select.mode.ts
Provides a new option `maintainShapeFrom` in select mode in the `feature` -> `coordinate` property. The possible options are:
* 'center' - the shape is maintained with it's origin at the center
* 'opposite' - the shape is maintained with the origin as the opposite bounding box point 
This is how you use it:
```typescript
new TerraDrawSelectMode({
flags: {
polygon: {
feature: {
draggable: true,
rotateable: true,
scaleable: true,
coordinates: {
midpoints: true,
draggable: true,
deletable: true,
maintainShapeFrom: "center"
},
},
},
```
This PR also fixes the fact that E2E tests were not actually running.
#183 #184
=> feat: allow maintaining shape when dragging coordinates in select mode

e2e/src/index.ts, e2e/tests/leaflet.spec.ts, e2e/tests/setup.ts
Adds in two E2E tests for `maintainShape` property introduced in #188. One for `center` option and another for the `opposite` option.
#189
=> test: add e2e tests for new maintainShape property in select mode

development/src/index.ts, e2e/src/index.ts, guides/4.MODES.md, src/geometry/transform/scale.ts, src/modes/select/behaviors/drag-coordinate-resize.behavior.spec.ts, src/modes/select/behaviors/drag-coordinate-resize.behavior.ts, src/modes/select/select.mode.spec.ts, src/modes/select/select.mode.ts
In hindsight, `maintainShapeFrom` was a bad API name and isn't very extensible. Changing it to `resizeable` is cleaner and allows for a host of different arguments to allow changing the aspect ratio of the shape in future. For now `center-fixed` and `opposite-corner-fixed` will be provided, with others to follow eventually
Building block for allowing #191
=> chore: refactor maintainShapeFrom to resizeable in select mode

guides/4.MODES.md, src/modes/select/select.mode.spec.ts, src/modes/select/select.mode.ts
Provides a flag for Select Mode, `allowManualDeselection` which when set to false, will prevent the user from being able to deselect when the click/tap on the map.
#186
=> feat: allow prevention of deselection on map click with new select mode parameter

development/src/index.ts, guides/3.ADAPTERS.md, src/adapters/arcgis-maps-sdk.adapter.ts, src/adapters/google-maps.adapter.spec.ts, src/adapters/google-maps.adapter.ts, src/adapters/leaflet.adapter.ts, src/adapters/mapbox-gl.adapter.ts, src/adapters/openlayers.adapter.ts, src/common.ts, src/terra-draw.ts, src/test/mock-callbacks.ts
Frustratingly Google Maps has an asynchronous aspect to it's setup when we add the OverlayView, we need to wait for it to be ready to get the projection from it, and it in turn it's methods for going from latitude, longitude to pixel space and vice versa.
To account for this a 'ready' event is added to Terra Draw, and Google Maps Adapter must wait for it be called before operating further with the Terra Draw instance.
To an extent the ready event may be generally useful for other adapters to, although the adapters will (in there existing state) _always_ be ready after calling 'start'.
#199
=> fix: create ready event which can be used by the Google Maps Adapter to avoid async issues

development/src/index.ts, guides/4.MODES.md, src/adapters/google-maps.adapter.ts, src/adapters/mapbox-gl.adapter.ts, src/modes/base.mode.ts, src/modes/select/select.mode.ts, src/terra-draw.spec.ts, src/terra-draw.ts
This PR allows users to programmatically select and deselect features using the public API. This gives a way to start Terra Draw and then immediately select a feature.
* add `deselectFeature`
* add `selectFeature`
#175
=> feat: allow users to select features programmatically

development/src/index.ts, e2e/src/index.ts, guides/4.MODES.md, src/modes/select/behaviors/drag-coordinate-resize.behavior.spec.ts, src/modes/select/behaviors/drag-coordinate-resize.behavior.ts, src/modes/select/select.mode.spec.ts, src/modes/select/select.mode.ts
* adds resize option of `opposite`
* prevent resizing polygons to be too small
[](https://github.com/JamesLMilner/terra-draw/issues/191)
=> feat: add opposite resizeable option for select mode

guides/4.MODES.md, src/modes/select/behaviors/drag-coordinate-resize.behavior.ts
It is noted that resizing uses geodesic transforms under the hood, so two planar options have been added for those not wanting to have visual distortions when resizing. 
No issue
=> feat: add planar options, opposite-planar and center-planar for resizeable in select mode

src/modes/select/select.mode.spec.ts, src/modes/select/select.mode.ts
Triggers 'finish' event on resizeable call
Adds unit test to ensure it works as expected
#209
=> fix: ensure 'finish' event is called for selected polygons with resizeable option

guides/4.MODES.md, src/modes/select/select.mode.spec.ts, src/modes/select/select.mode.ts
Before, you needed `draggable` to be true for `resizable` to work 
No issue
=> fix: make it so resizeable no longer requires draggable to be true to work

src/modes/select/behaviors/drag-coordinate-resize.behavior.ts
Fixes errors when resizing, due to errors thrown by some adapters project methods
#215
=> fix: ensure that project returns valid lat/lng when using resizable

e2e/tests/leaflet.spec.ts, src/modes/select/behaviors/drag-coordinate-resize.behavior.spec.ts, src/modes/select/behaviors/drag-coordinate-resize.behavior.ts
Fixes the issue when using `resizeable` that the cursor does not always correctly track the selection point when dragging, especially when done quickly or erratically. 
#214
Originally #191
=> fix: resizeable dragging should now track the cursor much more accurately

e2e/tests/leaflet.spec.ts, src/modes/select/behaviors/drag-coordinate-resize.behavior.ts
Prevents issue where you cross the origin axis and can still resize inside planar settings of `resizeable`. 
#218 
#191
=> fix: ensure that when using resizable you cannot resize after crossing origin axis

src/geometry/web-mercator-center.spec.ts, src/geometry/web-mercator-center.ts, src/modes/select/behaviors/drag-coordinate-resize.behavior.ts
It was not taking into account that the center was the geodesic center and not the web mercator center. This caused movement of the polygon as it was resized.
Potentially resolves #243 but hard to say without more feedback.
=> fix: Resolve issue with center-fixed-web-mercator and center-web-mercator

guides/4.MODES.md, src/common.ts, src/modes/select/behaviors/drag-coordinate-resize.behavior.spec.ts, src/modes/select/behaviors/drag-coordinate-resize.behavior.ts, src/modes/select/behaviors/drag-coordinate.behavior.spec.ts, src/modes/select/behaviors/drag-coordinate.behavior.ts, src/modes/select/behaviors/drag-feature.behavior.spec.ts, src/modes/select/behaviors/drag-feature.behavior.ts, src/modes/select/behaviors/rotate-feature.behavior.ts, src/modes/select/behaviors/scale-feature.behavior.ts, src/modes/select/select.mode.ts
Aims to provide a context object as the second parameter of the callback for the `validation` flag. This allows users to more easily project/unproject if they need to do things in pixel space.
Also creates a Validation type that can be reused when we move towards adding this for other built in modes too.
No issue
=> feat: add a context to allow more complex validations when selecting

development/src/index.ts, src/adapters/arcgis-maps-sdk.adapter.ts, src/adapters/common/base.adapter.ts, src/adapters/google-maps.adapter.ts, src/adapters/leaflet.adapter.ts, src/adapters/mapbox-gl.adapter.ts, src/adapters/maplibre-gl.adapter.ts, src/adapters/openlayers.adapter.ts
In #248 it was reported barebones tsc compilation when using the MapLibre Terra Draw Adapter was failing due to type errors. This is odd, as the offending method getCoordinatePrecision is implemented in the underlying abstract class for which the adapter extends. 
This PR attempts to fix this by explicitly declaring the methods in the extending adapters. This should mean they are always present, even if they are just a proxy for the underlying methods.
It would be great to understand why this as happened, as it seems as if it should be uncessary.
#248
=> fix: attempt to fix tsc build issues with implemented abstract methods

src/adapters/common/base.adapter.ts
The `contextmenu` event is triggering the adapter onClick, but right clicking already triggers a `pointerup` event. This leads to a 'double click' effect where both the `contextmenu` event and the `pointerup` event trigger onClick. 
The knock on consequence of this is #250 where two points are deleted. This PR should fix this - I don't think there should be any knock on consequences having manually tested it and examined the codepaths.
=> fix: remove trigger of onClick from contextmenu handler

tsconfig.json
Adds folders to the excludes property of `tsconfig.json` as VSCode complained it was having to traverse too many files
No issue
=> chore: actively exclude folders from tsc to keep IDEs happy

guides/6.EVENTS.md, src/common.ts, src/modes/base.mode.ts, src/modes/circle/circle.mode.spec.ts, src/modes/circle/circle.mode.ts, src/modes/freehand/freehand.mode.spec.ts, src/modes/freehand/freehand.mode.ts, src/modes/greatcircle/great-circle.mode.spec.ts, src/modes/greatcircle/great-circle.mode.ts, src/modes/linestring/linestring.mode.spec.ts, src/modes/linestring/linestring.mode.ts, src/modes/point/point.mode.ts, src/modes/polygon/polygon.mode.spec.ts, src/modes/polygon/polygon.mode.ts, src/modes/rectangle/rectangle.mode.spec.ts, src/modes/rectangle/rectangle.mode.ts, src/modes/select/select.mode.spec.ts, src/modes/select/select.mode.ts, src/terra-draw.ts
Adds context object to onFinish event to provide more context to how the finish event happened. This means you should be able to do this going forward:
```
draw.on("finish", (id: string, context: { action: string, mode: string }) => {
if (action === 'draw') {
// Do something for draw finish event
} else if (action === 'dragFeature') {
// Do something for a drag finish event
} else if (action === 'dragCoordinate') {
//
}else if (action === 'dragCoordinateResize') {
//
}
});
```
#253
=> feat: context object for onFinish to allow more control for developers

development/package-lock.json, development/package.json, e2e/package-lock.json, e2e/package.json, package-lock.json, package.json
Updates TypeScript across the codebase to version 5.5. Also bumps relating eslint packages to latest versions.
=> chore: bump to Typescript 5.5

src/adapters/arcgis-maps-sdk.adapter.spec.ts, src/adapters/common/adapter-listener.spec.ts, src/adapters/leaflet.adapter.spec.ts, src/adapters/mapbox-gl.adapter.spec.ts, src/modes/circle/circle.mode.spec.ts, src/modes/click-bounding-box.behavior.spec.ts, src/modes/freehand/freehand.mode.spec.ts, src/modes/linestring/linestring.mode.spec.ts, src/modes/point/point.mode.spec.ts, src/modes/polygon/behaviors/closing-points.behavior.spec.ts, src/modes/polygon/polygon.mode.spec.ts, src/modes/rectangle/rectangle.mode.spec.ts, src/modes/select/behaviors/drag-coordinate-resize.behavior.spec.ts, src/modes/select/behaviors/drag-coordinate.behavior.spec.ts, src/modes/select/behaviors/drag-feature.behavior.spec.ts, src/modes/select/behaviors/midpoint.behavior.spec.ts, src/modes/select/behaviors/rotate-feature.behavior.spec.ts, src/modes/select/behaviors/scale-feature.behavior.spec.ts, src/modes/select/select.mode.spec.ts, src/store/store.spec.ts
Removes all references to `toBeCalled`, `toBeCalledTimes`, `toBeCalledWith` and replaces with the non deprecated equivalents
=> chore: move all deprecated jest toBeCalled -> toHaveBeenCalled

e2e/src/index.ts, e2e/tests/leaflet.spec.ts, e2e/tests/setup.ts, guides/4.MODES.md, src/geometry/shape/create-circle.spec.ts, src/geometry/shape/create-circle.ts, src/geometry/shape/web-mercator-distortion.spec.ts, src/geometry/shape/web-mercator-distortion.ts, src/modes/circle/circle.mode.ts, src/modes/linestring/linestring.mode.ts
Default to drawing Web Mercator circles in TerraDrawCircleMode, with the option to draw geodesic circles using `projection: "globe"` 
#275
=> feat: add projection property for circle mode to allow globe and web mercator circle drawing

.github/pull_request_template.md, .github/workflows/conventional-commit-prs.yml, guides/7.DEVELOPMENT.md
Ensures that PRs can't have non conventional commit titles. This is to ensure the changelog is correctly generated.
#277
=> chore: add a action for ensuring conventional commits

src/modes/circle/circle.mode.ts, src/modes/freehand/freehand.mode.ts, src/modes/rectangle/rectangle.mode.ts
Minor fixes to ensure z-indexs are correct for circle, rectangle and freehand modes. This is mostly an issue in the Leaflet adapter.
No issue
=> fix: ensure the correct z-index for circle, rectangle, freehand

development/public/index.html, development/src/config.ts, development/src/index.ts
This PR allows the development page to be configurable in terms of which mapping library examples are initialised/rendered. 
#281
=> chore: allow configuration of loaded mapping libraries on the development page

.github/workflows/beta-release.yml
- The release-as was being passed an invalid release version. Hopefully fixing the script will resolve releases and allow for a beta release
No issue
=> chore: fix beta release script to set release-as flag correctly

src/adapters/openlayers.adapter.spec.ts
Add in a test for getLngLatFromEvent method in open layers adaptor
Slightly change the way we pass in the mock map in the adaptor for testing so this is easier to reuse
https://github.com/JamesLMilner/terra-draw/issues/90
=> test: add extra unit test to openlayers.adapter.spec

src/adapters/leaflet.adapter.spec.ts, src/adapters/leaflet.adapter.ts
Noticed at the codesprint - if containerPointToLatLng returned null or undefined the null value would not be returned
No issue
=> fix: ensure handling of containerPointToLatLng returning invalid values is handled correctly

src/modes/circle/circle.mode.ts, src/modes/freehand/freehand.mode.ts, src/modes/linestring/linestring.mode.ts, src/modes/polygon/polygon.mode.ts, src/modes/rectangle/rectangle.mode.ts
Because store changes can trigger events, we must reset the ids _before_ we go to delete, so if clear gets called again from the event, the ids are already reset, avoiding errors.
#304
=> fix: when clearing ensure ids are reset first before updating store as it may trigger events

README.md
Adds a small margin under the new logo to avoid visual clutter
No issue
=> chore: add margin to bottom of logo to avoid overcrowding in readme

README.md
The margin changes did not work aa it appears GitHub strips out style from the rendered readme. This approach should work.
No issue
=> chore: use linebreak under logo as margin does not work on github readme

guides/8.EXAMPLES.md
Adds maplibre-gl-terradraw to the examples guide
No issue
=> docs: add maplibre-gl-terradraw as an example to the examples guide

.github/workflows/beta-release-increment.yml, .github/workflows/ci.yml
Upgrades from v3 to v4 for actions/checkout and actions/setup-node
No issue
=> chore: upgrade github actions to the latest versions of checkout and setup-node

src/adapters/maplibre-gl.adapter.spec.ts
Adds unit tests for the MapLibre adapter. These are currently entirely based on the MapboxGL adapter tests as the API is still identical.
No issue
=> test: add MapLibre unit tests

guides/7.DEVELOPMENT.md, jest.config.ts, src/terra-draw.spec.ts
* Adds test coverage for `terra-draw.ts` file, i.e. the core Terra Draw API
* Sets the minimum test coverage to 80%
No issue
=> test: improve unit test coverage for terra-draw.ts and set unit test coverage threshold to 80%

development/src/index.ts, guides/3.ADAPTERS.md, src/adapters/openlayers.adapter.spec.ts, src/adapters/openlayers.adapter.ts
Add/display GeoJSON features with EPSG:4326 coordinates, when custom user projection set by user.
Since `ol/proj.transform()` uses defined projections in module, this PR add more inject items for openlayers adapter.
The following example use patched adapter:
- [EPSG:4326] WGS84
- [EPSG:3857] WGS 84 / Pseudo-Mercator
- [EPSG:3826] (Not built-in projection in `ol/proj`)
#319 
[EPSG:4326]: https://outdoorsafetylab.github.io/dumbymap/#%7B%22content%22%3A%22%60%60%60map%5Cnid%3A%204326%5Cnuse%3A%20https%3A%2F%2Funpkg.com%2Fmapclay%400.6.5%2Fdist%2Frenderers%2Fopenlayers.mjs%5Cnproj%3A%20EPSG%3A4326%5Cndraw%3A%20true%5Cncenter%3A%20%5B121%2C24%5D%5Cn%5Cn---%5Cn%5Cnconst%20coords%20%3D%20document.querySelector('%23coords')%3B%5Cnconst%20projection%20%3D%20ol.proj.getUserProjection().getCode()%3B% …
=> feat: add/read features by user projection in openlayers

src/modes/linestring/linestring.mode.spec.ts, src/modes/linestring/linestring.mode.ts
Ensures closing point is removed correctly for TerraDrawLineString mode when clean up is called
#340
=> fix: remove closing point correctly

guides/5.STYLING.md, src/modes/sector/sector.mode.spec.ts
Some tidy up where variables/docs were incorrectly referring to rectangle mode when they were for sector mode
No issue
=> chore: small tidy up in tests and docs for sector mode

src/modes/sensor/sensor.mode.spec.ts, src/modes/sensor/sensor.mode.ts
* Ensures that the linestring that gets generated whilst drawing the Sensor retains the same styling as the final polygon
No issue
=> fix: ensure TerraDrawSensorMode line arc can be styled correctly

src/modes/sensor/sensor.mode.ts
Makes it so the transition when moving the cursor inside the inner arc is smoother and doesn't leave a depth of greater than 0 when the cursor is inside the inner radius
No issue
=> fix: provide smoother transition of sensor depth when cursor goes into inner radius

guides/7.DEVELOPMENT.md, src/extend.ts, src/terra-draw.extensions.spec.ts, src/terra-draw.ts
Aims to improve the experience of creating your own custom modes and adapters by better exposing the types you need to create a custom adapter.
#342
=> fix: improve the extension object to make it easier to extend Terra Draw base adapters and modes

.npmignore
* Ensures the common folders are published to npm, which I believe has been causing type failures relating to `adapters/common.ts`
I think this partially resolves #350
=> fix: ensure that common folder files are published so types are not missing

development/src/index.ts, src/adapters/common/base.adapter.ts, src/adapters/openlayers.adapter.spec.ts, src/adapters/openlayers.adapter.ts
Fix TerraDrawOpenLayersAdapter not being able to handle multiple layers, preventing users from having more than one layer. This fix attempts to go a bit deeper, handling the scenario where layers are added or removed also. This is necessary because Terra Draw intercepts events on the 'top' canvas DOM element that is present in the browser. If we remove a layer or add layer we want to ensure the top layer is correct.
#357
=> fix: handle multiple layers in TerraDrawOpenLayersAdapter

src/modes/select/behaviors/drag-feature.behavior.spec.ts, src/modes/select/behaviors/drag-feature.behavior.ts, src/test/mock-behavior-config.ts
This change ensures that features are moved in a way that is appropriate for the provided `projection` that is passed to `TerraDrawSelectMode`
#359
=> fix: ensure that features are dragged in the projection set in TerraDrawSelectMode

development/src/index.ts, guides/3.ADAPTERS.md
* Adds the ArcGIS to the Adapter guide
* Fixes OpenLayers example to use `rendercomplete` rather than `postrender`
* Small tidy up to imports in the development index.ts file to make them more readable/simple
No issue
=> docs: improve adapter docs to include ArcGIS example

development/package-lock.json, development/package.json, e2e/package-lock.json, e2e/package.json, package-lock.json, package.json
This PR updates TypeScript to 5.6.3. It also updates the `typedoc` package to 0.26.11 as this was required for TypeScript 5.6.3 compatibility.
TypeScript updated in main folder, e2e folder, and development folder.
All tests still pass and no immediate issues identified.
Closes #363
=> chore: update TypeScript to 5.6

src/modes/circle/circle.mode.spec.ts, src/modes/circle/circle.mode.ts
Ensures that the visible Circle drawn which respects the `startingRadiusKilometers` if the users cursor does not move
#369
=> fix: create circle with minimum starting radius if there is no cursor movement

.github/workflows/ci.yml, guides/7.DEVELOPMENT.md
Makes use of the latest Node.js LTS, version 22
#368
=> chore: move GitHub actions and guidance to Node.js version 22 (current LTS)

src/modes/freehand/freehand.mode.spec.ts, src/modes/freehand/freehand.mode.ts
Adds the `closingPoint` property to freehand mode closing points to easily identify them as closing points
#365
=> fix: ensure that closingPoint property exists on closingPoint of freehand mode

development/src/config.ts, development/src/index.ts, src/modes/freehand/freehand.mode.spec.ts, src/modes/freehand/freehand.mode.ts
Adds autoclose feature to Freehand mode, allowing polygons to closed without clicking. This can be enabled with `autoClose: true` being provided to the mode. There is some basic protection against creating a new polygon if the user clicks by accident on the closing point. This is controllable via the `autoCloseTimeout` option property.
#367
=> feat: allow freehand features to be automatically closed with the autoClose option

guides/2.STORE.md, src/modes/base.mode.ts, src/modes/polygon/polygon.mode.ts, src/modes/rectangle/rectangle.mode.ts, src/modes/sector/sector.mode.ts, src/terra-draw.ts, src/validation-reasons.ts, src/validations/common-validations.ts, src/validations/linestring.validation.ts, src/validations/max-size.validation.ts, src/validations/min-size.validation.ts, src/validations/not-self-intersecting.validation.ts, src/validations/point.validation.ts, src/validations/polygon.validation.ts
This PR exposes all the internal validation failure reasons to make it easier for developers using Terra Draw to have branching logic depending on the failure reason, even if the wording of the error was to change in the future (for example due to a typo or clarification change).
```typescript
import { ValidationReasons } from 'terra-draw';
const { ValidationReasonFeatureHasHoles } = ValidationReasons
console.log(ValidationReasonFeatureHasHoles)
```
#380
=> feat: expose the validation failure reasons for developers to check against

development/src/index.ts, guides/4.MODES.md, src/common.ts, src/geometry/calculate-relative-angle.ts, src/geometry/clockwise.ts, src/geometry/determine-halfplane.ts, src/geometry/measure/bearing.ts, src/geometry/measure/destination.ts, src/geometry/measure/pixel-distance-to-line.ts, src/geometry/measure/pixel-distance.ts, src/geometry/point-on-line.spec.ts, src/geometry/point-on-line.ts, src/geometry/project/web-mercator.ts, src/geometry/transform/rotate.ts, src/geometry/web-mercator-centroid.ts, src/geometry/web-mercator-point-on-line.spec.ts, src/geometry/web-mercator-point-on-line.ts, src/modes/angled-rectangle/angled-rectangle.mode.ts, src/modes/coordinate-snapping.behavior.spec.ts, src/modes/coordinate-snapping.behavior.ts, src/modes/line-snapping.behavior.spec.ts, src/modes/line-snapping.behavior.ts, src/modes/linestring/linestring.mode.ts, src/modes/polygon/polygon.mode.spec.ts, src/modes/polygon/polygon.mode.ts, src/modes/select/behaviors/drag-coordinate-resize.behavior.ts
This PR sets up some breaking API changes for snapping, which paves the way for allowing snapping to lines as well as coordinates for the existing polygon mode features. Line and coordinate snapping can be enabled/disabled individually.
* Change polygon mode snapping property from optional boolean to optional object of type `{ toLine?: boolean;  toCoordinate?: boolean; }`
* Provides toLine which allows snapping to the line segments of polygon mode features
* Change linestring mode snapping property from optional boolean to optional object of type `{ toCoordinate?: boolean; }`
* Fixes bug with initial snapping of linestrings on the first coordinate click
* Add the `CartesianPoint` type to standardised x, y coordinates across the codebase …
=> feat: provide snapping to line as well as feature coordinates for polygon mode

development/src/index.ts, e2e/src/index.ts, e2e/tests/leaflet.spec.ts, e2e/tests/setup.ts, src/common.ts, src/modes/freehand/freehand.mode.ts, src/modes/linestring/linestring.mode.spec.ts, src/modes/linestring/linestring.mode.ts, src/modes/polygon/behaviors/closing-points.behavior.ts, src/modes/polygon/polygon.mode.spec.ts, src/modes/polygon/polygon.mode.ts
Provides visual feedback in the form of a point when snapping to line to make it clearer what is happening to the end user. The new behaviour looks like this:
#384
=> feat: visualise snapping point and allow it to be styled

development/src/index.ts, e2e/tests/leaflet.spec.ts, guides/4.MODES.md, src/modes/linestring/linestring.mode.spec.ts, src/modes/linestring/linestring.mode.ts, src/modes/polygon/polygon.mode.spec.ts, src/modes/polygon/polygon.mode.ts
This PR allows users to snap to some arbitrary position for Polygon and LineString modes. This can be useful in making it possible to snap to your own custom positions based on external data or some other criteria.
No issue
=> feat: allow snapping to custom positions with toCustom snapping option

.github/workflows/dry-run-release-terra-draw.yml
Adds a script that allows a dry-run release for the `terra-draw` package so we can see what changes will occur
No issue
=> chore(terra-draw): add a dry run release script for terra-draw

.github/workflows/release-terra-draw.yml
Ensures the script is named correctly for releasing terra-draw package
No issue
=> chore(terra-draw): ensure release script for terra-draw is named correctly

packages/terra-draw-arcgis-adapter/package.json
This PR will allow conventional commits to bump terra-draw-arcgis-maps-adapter to v1
#259
=> feat(terra-draw-arcgis-adapter)!: breaking change commit to allow adapter to v1.0.0

packages/terra-draw-google-maps-adapter/package.json
This PR will allow conventional commits to bump terra-draw-google-maps-adapter to v1
#259
=> feat(terra-draw-google-maps-adapter)!: breaking change commit to allow adapter to v1.0.0

packages/terra-draw-leaflet-adapter/package.json
This PR will allow conventional commits to bump terra-draw-leaflet-adapter to v1
#259
=> feat(terra-draw-leaflet-adapter)!: breaking change commit to allow adapter to v1.0.0

packages/terra-draw-maplibre-gl-adapter/package.json
This PR will allow conventional commits to bump terra-draw-maplibre-gl-adapter to v1
#259
=> feat(terra-draw-maplibre-gl-adapter)!: breaking change commit to allow adapter to v1.0.0

packages/terra-draw-openlayers-adapter/package.json
This PR will allow conventional commits to bump terra-draw-openlayers-adapter to v1
#259
=> feat(terra-draw-openlayers-adapter)!: breaking change commit to allow adapter to v1.0.0

package-lock.json, packages/development/package.json, packages/e2e/package.json
Ensures that local private packages use matching v1.0.0 version of terra-draw. Potentially we should automate this when releasing the `terra-draw` package?
#259
=> chore(terra-draw): bump e2e and development private packages to terra-draw v1.0.0

.github/workflows/terra-draw-arcgis-adapter-dry-run-release.yml, .github/workflows/terra-draw-arcgis-adapter-release.yml, .github/workflows/terra-draw-leaflet-adapter-dry-run-release.yml, .github/workflows/terra-draw-leaflet-adapter-release.yml, .github/workflows/terra-draw-mapbox-gl-adapter-dry-run-release.yml, .github/workflows/terra-draw-mapbox-gl-adapter-release.yml, .github/workflows/terra-draw-maplibre-gl-adapter-dry-run-release.yml, .github/workflows/terra-draw-maplibre-gl-adapter-release.yml, .github/workflows/terra-draw-openlayers-adapter-dry-run-release.yml, .github/workflows/terra-draw-openlayers-adapter-release.yml
We need to ensure terra-draw is built before trying to build the terra-draw adapters in releases
#259
=> chore(terra-draw): ensure terra-draw is built before trying to build adapters in releases

.github/workflows/terra-draw-leaflet-adapter-release.yml, package-lock.json
This PR aims to make it so we can update the root package-lock.json as part of the release to avoid CI failures on the main branch after the merge
#259
=> chore(terra-draw): add a step to update package-lock.json for Leaflet

.github/workflows/terra-draw-leaflet-adapter-release.yml
I think this causes issues because the package isn't initially published yet. Will remove for now.
#259
=> chore(terra-draw): remove package-lock.json update as part of release for now

package-lock.json, packages/e2e/package.json
Fixes the e2e tests package.json to reference correct version. We should look at automatically updating this on publish of the leaflet package.
#259
=> chore(terra-draw): fix leaflet adapter package version that does not exist for e2e package.json

guides/1.GETTING_STARTED.md
Resolves an issue in the docs where the example adapter is default imported
No issue
=> chore(terra-draw): fix the getting started guides Leaflet adapter import

packages/terra-draw-openlayers-adapter/README.md
PR aims to add a better documented README to the terra-draw-openlayers-adapter npm package.
No issue
=> fix(terra-draw-openlayers-adapter): ensure the README has correct links on npm

.github/workflows/terra-draw-arcgis-adapter-release.yml, .github/workflows/terra-draw-google-maps-adapter-dry-run-release.yml, .github/workflows/terra-draw-google-maps-adapter-release.yml, .github/workflows/terra-draw-leaflet-adapter-dry-run-release.yml, .github/workflows/terra-draw-leaflet-adapter-release.yml, .github/workflows/terra-draw-mapbox-gl-adapter-dry-run-release.yml, .github/workflows/terra-draw-mapbox-gl-adapter-release.yml, .github/workflows/terra-draw-maplibre-gl-adapter-dry-run-release.yml, .github/workflows/terra-draw-openlayers-adapter-dry-run-release.yml, .github/workflows/terra-draw-openlayers-adapter-release.yml, .github/workflows/terra-draw-release-dry-run.yml
Ensure that the root package-lock.json file is updated when a new package is released
No issue
=> chore(terra-draw): automatically update root package-lock.json on release by actions

packages/terra-draw-maplibre-gl-adapter/README.md
Fix a typo from Mapbox -> Maplibre in the Maplibre README
No issue
=> chore(terra-draw-maplibre-gl-adapter): fix typo in README

packages/terra-draw/src/modes/select/behaviors/drag-coordinate.behavior.ts
fix coordinates cannot be draggable if feature id is 0
https://github.com/JamesLMilner/terra-draw/issues/422
=> fix(terra-draw): resolve issue where coordinates cannot be draggable if feature id is 0

.github/workflows/commit-lint-prs.yml
Without the checkout action we don't actually get the repository code. This PR fixes that and ensures the branch is actually checked out correctly.
No issue
=> chore(terra-draw): ensure the actions/checkout action is used in the commit-lint-prs.yml action

.github/workflows/commit-lint-prs.yml
The current version of commit-lint-prs.yml does not install the packages, which I believe is causing it to use the latest version of commit-lint. This appears to be failing for a reason I haven't investigated, but as this works locally I assume it because two major versions different between what's installed and what is the latest version of commit-lint. This PR adds a `npm ci` to install the current versions.
No issue
=> chore(terra-draw): ensure that local version of commit lint is used for commit-lint-prs.yml

packages/e2e/src/index.ts, packages/e2e/tests/leaflet.spec.ts, packages/e2e/tests/setup.ts, packages/terra-draw/src/common.ts, packages/terra-draw/src/modes/point/point.mode.spec.ts, packages/terra-draw/src/modes/point/point.mode.ts
Gives an `editable` option to the `TerraDrawPointMode` which allows the points to me moved whilst still drawing. This allows for a closer experience to what OpenLayers offers out the box.
#433
=> feat(terra-draw): add editable option for point mode to allow moving points whilst drawing

guides/2.STORE.md
- para**met**er
- it **is** advisable...
- to **per**sist the data...
- strin**gi**fy
see:  
https://en.wiktionary.org/wiki/stringify
=> docs(terra-draw): fix spelling and grammar issues in 2.STORE.md

guides/8.EXAMPLES.md
- se**gm**ents
- capabilit**y**, ...
- **an** easy to use...
https://www.merriam-webster.com/dictionary/capabiliti
=> docs(terra-draw): fix spelling and indefinite article in 8.EXAMPLES.md

packages/e2e/src/index.ts, packages/e2e/tests/leaflet.spec.ts, packages/e2e/tests/setup.ts, packages/terra-draw/src/geometry/point-on-line.ts, packages/terra-draw/src/geometry/web-mercator-point-on-line.ts, packages/terra-draw/src/modes/coordinate-snapping.behavior.ts, packages/terra-draw/src/modes/line-snapping.behavior.ts, packages/terra-draw/src/modes/polygon/polygon.mode.spec.ts, packages/terra-draw/src/modes/polygon/polygon.mode.ts
Gives an editable option to the TerraDrawPolygonMode which allows the polygons to be edited whilst still drawing. This allows for a closer experience to what OpenLayers offers out the box.
https://github.com/JamesLMilner/terra-draw/issues/433
=> feat(terra-draw): add editable option for polygon mode to allow moving polygons whilst drawing

.github/ISSUE_TEMPLATE/documentation-improvement.md
Ensure a default title is provided for Documentation GitHub issue template
No issue
=> chore(terra-draw): add default title for the documentation issue template

guides/5.STYLING.md
- indivi**d**ual
- (e.**g.,** ...)
- clean**ed** up
https://www.merriam-webster.com/dictionary/e.g.#examples
=> docs(terra-draw): fix spelling and punctuation in 5.STYLING.md

packages/terra-draw/src/modes/select/select.mode.ts
Fixes an issue where a right click to delete code branch meant for polygons was getting hit for linestrings if the last coordinate was deleted.
#437
=> fix(terra-draw): fix issue deleting line string coordinate points in select mode

packages/terra-draw/src/terra-draw.spec.ts, packages/terra-draw/src/terra-draw.ts
Ensures `getFeaturesAtPointerEvent` can be passed with partial options, as defaults are provided  in `featuresAtLocation`
#435
=> fix(terra-draw): ensure getFeaturesAtPointerEvent has optional options properties

guides/4.MODES.md, guides/7.DEVELOPMENT.md, packages/development/src/index.ts, packages/terra-draw/src/modes/select/select.mode.spec.ts, packages/terra-draw/src/modes/select/select.mode.ts
* Use src rather than `dist` when referencing other packages from `development`
* Improve `7.DEVELOPMENT.md` to reflect changes 
* Small fixes to documentation around misspelt `resizeable` in docs
#448
=> chore(terra-draw): improve local development experience by using package src files rather than dist

bump.mjs, package-lock.json, package.json, packages/terra-draw-arcgis-adapter/package.json, packages/terra-draw-google-maps-adapter/package.json, packages/terra-draw-leaflet-adapter/package.json, packages/terra-draw-mapbox-gl-adapter/package.json, packages/terra-draw-maplibre-gl-adapter/package.json, packages/terra-draw-openlayers-adapter/package.json, packages/terra-draw/package.json
This is a work around for https://github.com/absolute-version/commit-and-tag-version/issues/210, where we pass the release type (patch, minor, major) to `--release-as` explicitly, as we can't seem to be able to filter out commits from other scopes in any other way. At the moment the change log filters out other commits from other scopes (packages) with the `transform` function. No similar function seems to exist for the bumping of the packages, so it sees all the breaking changes from the other packages since the last release.
=> chore(terra-draw): use --release-as with custom bumper as scopes are not being respected

package-lock.json, packages/terra-draw-openlayers-adapter/package.json
Fixes the build due to a missing caret for terra-draw-openlayers-adapter
No issue
=> chore(terra-draw-openlayers-adapter): fix carret missing from terra-draw dependency

bump.mjs, guides/7.DEVELOPMENT.md, package-lock.json, package.json
We can't rely on the existing script, so instead we go for something stripped back that allows us to handle exactly how we want to bump the packages.
No issue
=> chore(terra-draw): improve bump script to be more accurate in the recommended version

packages/e2e/src/index.ts, packages/e2e/tests/leaflet.spec.ts, packages/e2e/tests/setup.ts, packages/terra-draw/src/modes/linestring/linestring.mode.spec.ts, packages/terra-draw/src/modes/linestring/linestring.mode.ts, packages/terra-draw/src/modes/polygon/polygon.mode.ts
This brings the editable feature in line with point and polygon modes. 
#433
=> feat(terra-draw): add editable option for linestring mode to allow moving polygons whilst drawing

packages/e2e/tests/leaflet.spec.ts, packages/e2e/tests/setup.ts, packages/terra-draw/src/modes/linestring/linestring.mode.spec.ts, packages/terra-draw/src/modes/linestring/linestring.mode.ts, packages/terra-draw/src/modes/point/point.mode.spec.ts, packages/terra-draw/src/modes/point/point.mode.ts, packages/terra-draw/src/modes/polygon/polygon.mode.spec.ts, packages/terra-draw/src/modes/polygon/polygon.mode.ts
Adds right click deletion behaviour to match select mode for `editable` properties for Point, LineString and Polygon
#433
=> feat(terra-draw): allow deletion of coordinates with right clicks when editable is true

packages/terra-draw/src/geometry/boolean/right-hand-rule.spec.ts, packages/terra-draw/src/geometry/boolean/right-hand-rule.ts, packages/terra-draw/src/geometry/ensure-right-hand-rule.spec.ts, packages/terra-draw/src/geometry/ensure-right-hand-rule.ts, packages/terra-draw/src/modes/angled-rectangle/angled-rectangle.mode.spec.ts, packages/terra-draw/src/modes/angled-rectangle/angled-rectangle.mode.ts, packages/terra-draw/src/modes/circle/circle.mode.spec.ts, packages/terra-draw/src/modes/freehand/freehand.mode.spec.ts, packages/terra-draw/src/modes/freehand/freehand.mode.ts, packages/terra-draw/src/modes/polygon/polygon.mode.spec.ts, packages/terra-draw/src/modes/polygon/polygon.mode.ts, packages/terra-draw/src/modes/rectangle/rectangle.mode.spec.ts, packages/terra-draw/src/modes/rectangle/rectangle.mode.ts, packages/terra-draw/src/modes/sector/sector.mode.spec.ts, packages/terra-draw/src/modes/sector/sector.mode.ts, packages/terra-draw/src/modes/sensor/sensor.mode.spec.ts, packages/terra-draw/src/modes/sensor/sensor.mode.ts
Helps ensure that polygons are created following the [Right Hand Rule](https://en.wikipedia.org/wiki/Right-hand_rule)
No issue
=> fix(terra-draw): ensure that polygons created by builtin modes abide by right hand rule

package-lock.json, packages/e2e/package.json
Fixs the build for 1.2.0
No issue
=> chore(terra-draw): fix build due to e2e package.json referencing terra-draw v1.1.0

package-lock.json, packages/development/package.json, packages/e2e/package.json
They are pointing at the wrong versions. Long term we should automatically bump these on release.
No issue
=> chore(terra-draw): update the e2e and development package terra-draw and adapter versions

packages/terra-draw-leaflet-adapter/src/terra-draw-leaflet-adapter.spec.ts, packages/terra-draw-leaflet-adapter/src/terra-draw-leaflet-adapter.ts
Fixes issue where deleted features were getting re-rendered because they are not deleted from the internal map of layers. We now delete them from that map. Also does not schedule so many rAFs as one is enough per style change. 
https://github.com/JamesLMilner/terra-draw/issues/472
=> fix(terra-draw-leaflet-adapter): ensure deleted features are removed from layer state

package-lock.json, packages/e2e/package.json, update.mjs
Adds a script that can be run (eventually on CI) which bumps all the necessary packages.
https://github.com/JamesLMilner/terra-draw/issues/486
=> chore(terra-draw): add a script that can bump all necessary packages

packages/terra-draw/src/modes/linestring/linestring.mode.ts, packages/terra-draw/src/modes/polygon/polygon.mode.spec.ts, packages/terra-draw/src/modes/polygon/polygon.mode.ts
This PR ensures that we filter out features that are not in the current mode for Polygon and LineString modes
https://github.com/JamesLMilner/terra-draw/issues/481
=> fix(terra-draw): ensure that editable only allows updating features in the current mode

packages/terra-draw-leaflet-adapter/src/terra-draw-leaflet-adapter.ts
TerraDrawLeafletAdapter was using polygonFillColor to set the stroke color of polygons.
I changed this to polygonOutlineColor instead
https://github.com/JamesLMilner/terra-draw/issues/493
=> fix(terra-draw-leaflet-adapter): use polygonOutlineColor instead of polygonFillColor for color

package-lock.json, packages/e2e/package.json
Updates e2e package.json file to use terra-draw-leaflet-adapter-version v1.0.3. Long term we need to run update.mjs on every release.
No issue but CI is failing
=> chore(terra-draw): ensure e2e test package is using latest terra-draw-leaflet-adapter version

guides/4.MODES.md, packages/e2e/tests/leaflet.spec.ts, packages/terra-draw/src/modes/select/select.mode.spec.ts, packages/terra-draw/src/modes/select/select.mode.ts
Allows a midpoint to be dragged immediately from it's initial state in a similar to way to selection points for Select mode.
[[Feature Request] Draggable midpoints](https://github.com/JamesLMilner/terra-draw/issues/496)
=> feat(terra-draw): allow dragging of midpoints in select mode by passing a flag

packages/terra-draw/src/geometry/boolean/is-valid-coordinate.spec.ts, packages/terra-draw/src/geometry/boolean/is-valid-coordinate.ts, packages/terra-draw/src/modes/insert-coordinates.behavior.spec.ts, packages/terra-draw/src/modes/select/behaviors/drag-coordinate-resize.behavior.ts, packages/terra-draw/src/terra-draw.spec.ts, packages/terra-draw/src/validation-reasons.ts, packages/terra-draw/src/validations/linestring.validation.spec.ts, packages/terra-draw/src/validations/linestring.validation.ts, packages/terra-draw/src/validations/point.validation.spec.ts, packages/terra-draw/src/validations/point.validation.ts, packages/terra-draw/src/validations/polygon.validation.spec.ts, packages/terra-draw/src/validations/polygon.validation.ts
Originally raised by @JinIgarashi - thank you! I have built on his original commits just making some additional changes to avoid double looping and to add some more tests
At a high level this ensures that excessive precision is handled separately and you get a specific error message when the precision is higher than what is defined by the adapter.
fixes #490
=> fix(terra-draw): added new ValidationReason if feature has excessive coordinate precision

packages/terra-draw-maplibre-gl-adapter/src/terra-draw-maplibre-gl-adapter.spec.ts, packages/terra-draw-maplibre-gl-adapter/src/terra-draw-maplibre-gl-adapter.ts
Fixes a long standing issue where initial dragRotate and dragPan are not respected when we need to call `setDraggability`. We do this so we can do our own custom behaviours without rotating or panning the map, but in the scenario the user has already disabled these we do not need to turn them back on.  
https://github.com/JamesLMilner/terra-draw/issues/391
=> fix(terra-draw-maplibre-gl-adapter): respect dragRotate and dragPan settings at initialisation

packages/terra-draw/src/modes/linestring/linestring.mode.spec.ts, packages/terra-draw/src/modes/linestring/linestring.mode.ts, packages/terra-draw/src/modes/polygon/polygon.mode.spec.ts, packages/terra-draw/src/modes/polygon/polygon.mode.ts
This PR ensures that a `finish` event is triggered when editing action is completed in polygon and linestring modes. Previously no event was triggered which made it hard to know when the edit was completed.
https://github.com/JamesLMilner/terra-draw/issues/506
=> fix(terra-draw): edits made via the editable option now trigger a finish event

packages/terra-draw-arcgis-adapter/src/terra-draw-arcgis-adapter.spec.ts, packages/terra-draw-arcgis-adapter/src/terra-draw-arcgis-adapter.ts
Adds basic zIndex support for the ArcGIS adapter, this needs improving long term to handle zindexing properly.
No issue
=> fix(terra-draw-arcgis-adapter): initial handling of zIndexes in the render function

packages/terra-draw-google-maps-adapter/src/terra-draw-google-maps-adapter.ts
Adds simple handling for zIndexs in the Google Maps adapter
No issue
=> fix(terra-draw-google-maps-adapter): initial handling of zIndexes in the render function 

packages/terra-draw-openlayers-adapter/src/terra-draw-openlayers-adapter.ts
Adds basic support for zindexes for the OpenLayers adapter
No issue
=> fix(terra-draw-openlayers-adapter): initial handling of zIndexes in the render function

packages/terra-draw-mapbox-gl-adapter/src/terra-draw-mapbox-gl-adapter.spec.ts, packages/terra-draw-mapbox-gl-adapter/src/terra-draw-mapbox-gl-adapter.ts
This PR allows handling of layered points by creating a separate layer for points that sit under the main points layer
No issue
=> fix(terra-draw-mapbox-gl-adapter): better handle zindexes to support layered points

packages/e2e/src/index.ts, packages/e2e/tests/leaflet.spec.ts, packages/e2e/tests/setup.ts, packages/terra-draw/src/common.ts, packages/terra-draw/src/modes/base.mode.ts, packages/terra-draw/src/modes/polygon/polygon.mode.spec.ts, packages/terra-draw/src/modes/polygon/polygon.mode.ts, packages/terra-draw/src/modes/select/behaviors/coordinate-point.behavior.spec.ts, packages/terra-draw/src/modes/select/behaviors/coordinate-point.behavior.ts, packages/terra-draw/src/modes/select/behaviors/drag-coordinate-resize.behavior.spec.ts, packages/terra-draw/src/modes/select/behaviors/drag-coordinate-resize.behavior.ts, packages/terra-draw/src/modes/select/behaviors/drag-coordinate.behavior.spec.ts, packages/terra-draw/src/modes/select/behaviors/drag-coordinate.behavior.ts, packages/terra-draw/src/modes/select/behaviors/drag-feature.behavior.spec.ts, packages/terra-draw/src/modes/select/behaviors/drag-feature.behavior.ts, packages/terra-draw/src/modes/select/behaviors/feature-at-pointer-event.behavior.ts, packages/terra-draw/src/modes/select/behaviors/midpoint.behavior.spec.ts, packages/terra-draw/src/modes/select/behaviors/midpoint.behavior.ts, packages/terra-draw/src/modes/select/behaviors/rotate-feature.behavior.spec.ts, packages/terra-draw/src/modes/select/behaviors/rotate-feature.behavior.ts, packages/terra-draw/src/modes/select/behaviors/scale-feature.behavior.spec.ts, packages/terra-draw/src/modes/select/behaviors/scale-feature.behavior.ts, packages/terra-draw/src/modes/select/select.mode.ts, packages/terra-draw/src/store/store.ts, packages/terra-draw/src/terra-draw.ts
This PR attempts to add the concept of 'coordinate points' to polygon mode, so that all coordinates of a polygon geometry are always rendered whilst drawing. 
No issue
=> feat(terra-draw): add showCoordinatePoints to provide a way to render coordinate points for polygons

packages/e2e/src/index.ts
At the moment the example config is typed to `any`. Using a class gives us better typings and strongly types `this.config`. It also allows for better configurability options in future.
No issue
=> chore(terra-draw): use a class to get better typings when setting up map/draw for the e2e tests

guides/4.MODES.md, packages/development/src/index.ts, packages/e2e/src/index.ts, packages/e2e/tests/leaflet.spec.ts, packages/e2e/tests/setup.ts, packages/terra-draw/src/modes/select/behaviors/drag-coordinate.behavior.spec.ts, packages/terra-draw/src/modes/select/behaviors/drag-coordinate.behavior.ts, packages/terra-draw/src/modes/select/select.mode.spec.ts, packages/terra-draw/src/modes/select/select.mode.ts
Provides a way to snap to other coordinates in select mode for geometries of the same mode. You can now configure flags like so in TerraDrawSelectMode:
```typescript
new TerraDrawSelectMode({
projection: "web-mercator",
flags: {
polygon: {
feature: {
coordinates: {
snappable: true,
midpoints: true,
draggable: true,
deletable: true,
},
},
},
```
Then you would be able to drag coordinates in select mode for linestrings mode geometries and snap them to other linestring geometry coordinates.
https://github.com/JamesLMilner/terra-draw/issues/507
=> feat(terra-draw): add snappable as an option for dragging geometry coordinates in select mode

packages/terra-draw/src/modes/select/behaviors/drag-coordinate.behavior.ts, packages/terra-draw/src/modes/select/select.mode.ts, packages/terra-draw/src/store/store.ts, packages/terra-draw/src/terra-draw.spec.ts, packages/terra-draw/src/terra-draw.ts
Ensures that coordinate, mid and selection points are all deleted correctly when a related feature is deleted.
https://github.com/JamesLMilner/terra-draw/issues/520
=> fix(terra-draw): delete coordinate, mid and selection points on calls to removeFeatures

packages/terra-draw/src/modes/select/behaviors/coordinate-point.behavior.spec.ts, packages/terra-draw/src/modes/select/behaviors/coordinate-point.behavior.ts, packages/terra-draw/src/terra-draw.spec.ts
Currently we do not handle the case where the coordinatePointIds associated with a polygon mode feature might have been deleted or not exist. This attempts to handle that scenario better.
#520
=> fix(terra-draw): account for coordinate points potentially not existing

packages/terra-draw-maplibre-gl-adapter/src/terra-draw-maplibre-gl-adapter.spec.ts, packages/terra-draw-maplibre-gl-adapter/src/terra-draw-maplibre-gl-adapter.ts
Currently the coordinate point layer (td-point-lower) is not being cleaned up correctly. This PR corrects that.
No issue
=> fix(terra-draw-maplibre-gl-adapter): ensure lower point layer is cleaned up correctly

packages/terra-draw/src/extend.ts, packages/terra-draw/src/terra-draw.ts
This PR aims to make it easier to type code from the Terra Draw API, and also to extend Terra Draw by exposing types for creating your own adapters and modes.
Thanks to @ciscorn for helping push this through.
https://github.com/JamesLMilner/terra-draw/issues/439
=> chore(terra-draw): export additional types for easier typing and extension 

guides/6.EVENTS.md, packages/terra-draw/src/common.ts, packages/terra-draw/src/modes/angled-rectangle/angled-rectangle.mode.spec.ts, packages/terra-draw/src/modes/base.behavior.ts, packages/terra-draw/src/modes/base.mode.ts, packages/terra-draw/src/modes/circle/circle.mode.spec.ts, packages/terra-draw/src/modes/freehand/freehand.mode.spec.ts, packages/terra-draw/src/modes/linestring/linestring.mode.spec.ts, packages/terra-draw/src/modes/point/point.mode.spec.ts, packages/terra-draw/src/modes/polygon/polygon.mode.spec.ts, packages/terra-draw/src/modes/rectangle/rectangle.mode.spec.ts, packages/terra-draw/src/modes/sector/sector.mode.spec.ts, packages/terra-draw/src/modes/select/select.mode.spec.ts, packages/terra-draw/src/modes/sensor/sensor.mode.spec.ts, packages/terra-draw/src/store/store.spec.ts, packages/terra-draw/src/store/store.ts, packages/terra-draw/src/terra-draw.spec.ts, packages/terra-draw/src/terra-draw.ts, packages/terra-draw/src/test/mock-mode-config.ts
This PR ensures that changes from the API can be filtered out/differentiated from changes coming from inside modes (i.e. generally from user interactions).
#527
=> feat(terra-draw): add context object when onChange is called via the Terra Draw API

packages/terra-draw/src/common.ts, packages/terra-draw/src/modes/angled-rectangle/angled-rectangle.mode.ts, packages/terra-draw/src/modes/circle/circle.mode.ts, packages/terra-draw/src/modes/freehand/freehand.mode.ts, packages/terra-draw/src/modes/linestring/linestring.mode.ts, packages/terra-draw/src/modes/point/point.mode.ts, packages/terra-draw/src/modes/polygon/polygon.mode.ts, packages/terra-draw/src/modes/rectangle/rectangle.mode.ts, packages/terra-draw/src/modes/sector/sector.mode.ts, packages/terra-draw/src/modes/select/select.mode.ts, packages/terra-draw/src/modes/sensor/sensor.mode.ts
It is more maintainable to have a centralised zIndexing constant that we can rely on for different layers. We currently support 5 layers.
No issue
=> chore(terra-draw): use a constant for feature zIndexing

packages/terra-draw/src/common.ts, packages/terra-draw/src/modes/select/behaviors/coordinate-point.behavior.spec.ts, packages/terra-draw/src/modes/select/behaviors/coordinate-point.behavior.ts
- Adds a property to the coordinate point features to determine which feature they are associated to. This is useful if you want to style them based on a specific feature id for example.
No issue
=> feat(terra-draw): add a way to determine which feature a coordinate point relates to

docs/media/3.ADAPTERS.md
Makes a small change to the code example for MapLibre/Mapbox in the adapters guide to make sure the base map styles are properly loaded first.
https://github.com/JamesLMilner/terra-draw/issues/533
=> docs(terra-draw): add style-load event to guides for Mapbox/MapLibre

packages/terra-draw/src/common.ts, packages/terra-draw/src/common/base.adapter.ts, packages/terra-draw/src/modes/polygon/polygon.mode.spec.ts, packages/terra-draw/src/modes/polygon/polygon.mode.ts, packages/terra-draw/src/modes/select/select.mode.spec.ts, packages/terra-draw/src/modes/select/select.mode.ts, packages/terra-draw/src/test/mock-cursor-event.ts
Some users would like to be able to delete via the contextmenu event (i.e. Ctrl + Click on MacOS, long press on Android/iOS). This PR provides a way to enable this and allow deleting coordinates via this method.
https://github.com/JamesLMilner/terra-draw/issues/528
=> feat(terra-draw): allow coordinate deletions with contextmenu events

packages/terra-draw-maplibre-gl-adapter/src/terra-draw-maplibre-gl-adapter.spec.ts, packages/terra-draw-maplibre-gl-adapter/src/terra-draw-maplibre-gl-adapter.ts
Here we can remove an unnecessary layer for the points and instead use the sort-key layout property. We can't do full zIndexing as I would like because we h
Partially related to https://github.com/JamesLMilner/terra-draw/issues/394 but doesn't fully resolve it
=> chore(terra-draw-maplibre-gl-adapter): use sort-key rather than extra  point layer ordering

packages/terra-draw-maplibre-gl-adapter/src/terra-draw-maplibre-gl-adapter.spec.ts, packages/terra-draw-maplibre-gl-adapter/src/terra-draw-maplibre-gl-adapter.ts
At the moment clear removes layers and unregister does not (although unregister would have been calling clear which removes the layers!). This means that clear could never be called more than once, and also once you cleared you could no longer draw.
We now just empty out the layers on clear and then on unregister actually remove the sources and layers.
No issue
=> fix(terra-draw-maplibre-gl-adapter): fix clear and unregister methods

guides/4.MODES.md, packages/e2e/src/index.ts, packages/e2e/tests/leaflet.spec.ts, packages/e2e/tests/setup.ts, packages/terra-draw/src/modes/angled-rectangle/angled-rectangle.mode.spec.ts, packages/terra-draw/src/modes/angled-rectangle/angled-rectangle.mode.ts, packages/terra-draw/src/modes/base.mode.ts, packages/terra-draw/src/modes/circle/circle.mode.spec.ts, packages/terra-draw/src/modes/circle/circle.mode.ts, packages/terra-draw/src/modes/freehand/freehand.mode.spec.ts, packages/terra-draw/src/modes/freehand/freehand.mode.ts, packages/terra-draw/src/modes/linestring/linestring.mode.spec.ts, packages/terra-draw/src/modes/linestring/linestring.mode.ts, packages/terra-draw/src/modes/point/point.mode.spec.ts, packages/terra-draw/src/modes/point/point.mode.ts, packages/terra-draw/src/modes/polygon/polygon.mode.spec.ts, packages/terra-draw/src/modes/polygon/polygon.mode.ts, packages/terra-draw/src/modes/rectangle/rectangle.mode.spec.ts, packages/terra-draw/src/modes/rectangle/rectangle.mode.ts, packages/terra-draw/src/modes/sector/sector.mode.ts, packages/terra-draw/src/modes/select/select.mode.spec.ts, packages/terra-draw/src/modes/select/select.mode.ts, packages/terra-draw/src/modes/sensor/sensor.mode.spec.ts, packages/terra-draw/src/modes/sensor/sensor.mode.ts
This aims to allow interception of pointer events for modes. There may be reasons that users do not want an pointer event to perform any actual state changes, and as such providing a way to conditionally disable these is useful
This is partially related to https://github.com/JamesLMilner/terra-draw/issues/169 although it tackles it at the mode level rather than at the adapter level. It should be able to resolve the issue mentioned in that issue however.
=> feat(terra-draw): allow filtering of pointer events with a function or boolean

packages/terra-draw/src/modes/linestring/linestring.mode.ts, packages/terra-draw/src/modes/point/point.mode.ts, packages/terra-draw/src/modes/polygon/polygon.mode.ts
Ensures draggability isn't set to true whilst dragging to edit a polygons, linestrings or points when `editable` is enabled in those modes. This fixes the `editable` behaviour for a few adapters.
[[Bug] Editable polygon coordinates are not working in OpenLayers, Google Maps and ArcGIS adapters](https://github.com/JamesLMilner/terra-draw/issues/510)
=> fix(terra-draw):  when editable is true in supported modes do not enable draggability on drag

packages/terra-draw/README.md
Fixes the link to `terra-draw-mapbox-gl-adapter` in the README for terra-draw package
No issue
=> docs(terra-draw): ensure README link to terra-draw-mapbox-gl-js-adapter is correct

guides/3.ADAPTERS.md
This change was already made in https://github.com/JamesLMilner/terra-draw/pull/537 but looks like it wasn't made to the source file. This PR fixes that and wraps the MapbLibre and Mapbox examples in the style.load event as is required.
https://github.com/JamesLMilner/terra-draw/issues/547
=> docs(terra-draw): ensure style.load event is wrapping MapLibre and Mapbox examples

packages/terra-draw/src/geometry/measure/bearing.spec.ts, packages/terra-draw/src/geometry/measure/bearing.ts, packages/terra-draw/src/geometry/web-mercator-centroid.spec.ts, packages/terra-draw/src/modes/select/behaviors/rotate-feature.behavior.spec.ts, packages/terra-draw/src/modes/select/behaviors/rotate-feature.behavior.ts, packages/terra-draw/src/modes/select/behaviors/scale-feature.behavior.ts
Currently we retrieve the updated geometry on every rotation and recalculate it's centroid from the store every time. This causes strange rotation behaviours for very small geometries. We can avoid this and for rotation as the center should remain the same on rotation.
https://github.com/JamesLMilner/terra-draw/issues/548
=> fix(terra-draw): improve rotating behaviour for geographically small geometries

packages/terra-draw/src/modes/select/behaviors/drag-coordinate-resize.behavior.ts, packages/terra-draw/src/modes/select/behaviors/scale-feature.behavior.spec.ts, packages/terra-draw/src/modes/select/behaviors/scale-feature.behavior.ts, packages/terra-draw/src/modes/select/select.mode.ts
Here we reuse the `center-fixed` behaviour from `DragCoordinateResizeBehavior` to fix an issue where scaling a polygon was not tracking the coordinate being dragged correctly. This has the added bonus of not maintaining two very similar code paths and the behaviour for both being consistent.
https://github.com/JamesLMilner/terra-draw/issues/551
=> fix(terra-draw): resolve  scaling in select mode not tracking cursor correctly

packages/terra-draw-mapbox-gl-adapter/src/terra-draw-mapbox-gl-adapter.spec.ts, packages/terra-draw-mapbox-gl-adapter/src/terra-draw-mapbox-gl-adapter.ts
The Mapbox GL Adapter has been lagging behind the MapLibre GL Adapter. This MR brings it inline with the improvements made there. This has the benefit of fixing an open bug ticket to do with clearing geometries.
https://github.com/JamesLMilner/terra-draw/issues/553
=> feat(terra-draw-mapbox-gl-adapter): bring up to parity with changes in maplibre adapter

packages/e2e/public/index.html, packages/e2e/src/index.ts, packages/e2e/tests/leaflet.spec.ts, packages/e2e/tests/setup.ts, packages/terra-draw/src/common/base.adapter.ts, packages/terra-draw/src/modes/point/point.mode.ts, packages/terra-draw/src/terra-draw.extensions.spec.ts, packages/terra-draw/src/terra-draw.spec.ts, packages/terra-draw/src/terra-draw.ts
**Behavior**
* Only call register logic if `enabled` is currently `false`, only call unregister logic if `enabled` is current `true`. This avoids situations where the register logic is not idempotent and could cause errors or unpredictable state.
* In the base adapter we now set `_currentModeCallbacks` to `undefined` as in the adapter `clear` methods we are checking to ensure the adapter is registered correctly. Since `unregister` was never setting this, there are clear methods in the adapters that check that this value is true, assuming the adapter is registered when it is not.
* Remove inconsistent check in point mode where we check the store is present
**Tests**
* Improves unit testing around enabled/disabled logic
* Add an end-to-end test for stop and starting Terra Draw with a real …
=> fix(terra-draw): avoid calling register/unregister when state is already enabled/disabled

guides/4.MODES.md, packages/e2e/src/index.ts, packages/e2e/tests/leaflet.spec.ts, packages/e2e/tests/setup.ts, packages/terra-draw/src/common.ts, packages/terra-draw/src/modes/linestring/linestring.mode.spec.ts, packages/terra-draw/src/modes/linestring/linestring.mode.ts, packages/terra-draw/src/modes/polygon/polygon.mode.ts, packages/terra-draw/src/modes/select/behaviors/drag-coordinate.behavior.spec.ts, packages/terra-draw/src/modes/select/behaviors/drag-coordinate.behavior.ts, packages/terra-draw/src/modes/select/select.mode.spec.ts, packages/terra-draw/src/modes/select/select.mode.ts
Unifies how snapping is handled across polygon, linestring and select modes. This will allow `toCoordinate`, `toLine` and `toCustom` behaviours in all 3 modes, powered by the same code.
https://github.com/JamesLMilner/terra-draw/issues/561
https://github.com/JamesLMilner/terra-draw/issues/343
=> feat(terra-draw): unify snapping functionality across polygon, linestring and select modes

guides/6.EVENTS.md, packages/terra-draw/src/terra-draw.spec.ts, packages/terra-draw/src/terra-draw.ts
This PR allows for returning polygon features that are within the pointer distance if `includePolygonsWithinPointerDistance` is set true. Also provides some additional options for filtering out other guidance features that developers might find helpful.
No issue
=> feat(terra-draw): get nearby polygons with getFeaturesAtLngLat/getFeaturesAtPointerEvent

packages/terra-draw/src/terra-draw.spec.ts, packages/terra-draw/src/terra-draw.ts
A comment was raised on a previous PR about how this wasn't actually included in the code and only in the options argument. This is true and so with this PR we ensure that `includePolygonsWithinPointerDistance` actually controls the ability to include polygons within the pointer distance.
Original comment:
https://github.com/JamesLMilner/terra-draw/pull/576#issuecomment-3018577971
No issue
=> fix(terra-draw): ensure includePolygonsWithinPointerDistance works correctly

guides/2.STORE.md, packages/terra-draw/src/modes/angled-rectangle/angled-rectangle.mode.spec.ts, packages/terra-draw/src/modes/angled-rectangle/angled-rectangle.mode.ts, packages/terra-draw/src/modes/base.mode.ts, packages/terra-draw/src/modes/circle/circle.mode.spec.ts, packages/terra-draw/src/modes/circle/circle.mode.ts, packages/terra-draw/src/modes/freehand/freehand.mode.spec.ts, packages/terra-draw/src/modes/freehand/freehand.mode.ts, packages/terra-draw/src/modes/linestring/linestring.mode.spec.ts, packages/terra-draw/src/modes/linestring/linestring.mode.ts, packages/terra-draw/src/modes/point/point.mode.spec.ts, packages/terra-draw/src/modes/point/point.mode.ts, packages/terra-draw/src/modes/polygon/polygon.mode.spec.ts, packages/terra-draw/src/modes/polygon/polygon.mode.ts, packages/terra-draw/src/modes/rectangle/rectangle.mode.spec.ts, packages/terra-draw/src/modes/rectangle/rectangle.mode.ts, packages/terra-draw/src/modes/sector/sector.mode.spec.ts, packages/terra-draw/src/modes/sector/sector.mode.ts, packages/terra-draw/src/modes/select/select.mode.spec.ts, packages/terra-draw/src/modes/select/select.mode.ts, packages/terra-draw/src/modes/sensor/sensor.mode.spec.ts, packages/terra-draw/src/modes/sensor/sensor.mode.ts, packages/terra-draw/src/terra-draw.spec.ts, packages/terra-draw/src/terra-draw.ts
This adds a API method `updateFeatureGeometry` that allows developers to programmatically update the geometry of a feature. This can be useful if you want to avoid deleting and re-adding a feature, or if you want to mutate a geometry via some user input like a button or numeric input field. An example might be you want to be able to simplify a given polygon on demand.
https://github.com/JamesLMilner/terra-draw/issues/557
=> feat(terra-draw): add updateFeatureGeometry to the API

packages/terra-draw-mapbox-gl-adapter/src/terra-draw-mapbox-gl-adapter.ts
zIndex was not being set for LineStrings or Polygons, which causes a warning when it tries to get the zIndex property on these layers. I think this may have been deliberate because internally in the built-in modes we do not differentiate between linestrings and polygon zIndexes. This PR ensures that it is always set. 
Note, a code comment has been added about the complexity that render order is predominately controlled by layer ordering, then within the same layer by the `sort-key`. 
#607
=> fix(terra-draw-mapbox-gl-adapter): ensure zIndex is set for all geometry types

packages/terra-draw/src/modes/linestring/linestring.mode.spec.ts, packages/terra-draw/src/modes/linestring/linestring.mode.ts
Closing points were not styleable in TerraDrawLineString mode as the closing point property was not being applied correctly. This is resolved in this PR
#633
=> fix(terra-draw): ensure closing points for linestring mode are styleable

README.md
Tiny PR to keep badge colors consistent in the README
No issue
=> chore(terra-draw): ensure badge colors in README are consistent

packages/terra-draw-google-maps-adapter/src/terra-draw-google-maps-adapter.spec.ts, packages/terra-draw-google-maps-adapter/src/terra-draw-google-maps-adapter.ts
Google Maps' version of Feature does not match the GeoJSON specification, having getX() methods instead of X property.
The feature id was the only one that was ignored for the styling functions call. 
This has been rectified.
As described in the Google Maps API documentation, provided the feature id to styling functions.
https://github.com/JamesLMilner/terra-draw/issues/639
=> fix(terra-draw-google-maps-adapter): feature id was not set in the style rendering functions

guides/2.STORE.md, packages/storybook/src/common/stories.ts, packages/storybook/src/stories/arcgis/ArcGIS.stories.ts, packages/storybook/src/stories/google/Google.stories.ts, packages/storybook/src/stories/leaflet/Leaflet.stories.ts, packages/storybook/src/stories/mapbox/Mapbox.stories.ts, packages/storybook/src/stories/maplibre/MapLibre.stories.ts, packages/storybook/src/stories/openlayers/OpenLayers.stories.ts, packages/terra-draw/src/common.ts, packages/terra-draw/src/store/store.ts, packages/terra-draw/src/store/valid-json.spec.ts, packages/terra-draw/src/store/valid-json.ts, packages/terra-draw/src/terra-draw.spec.ts, packages/terra-draw/src/terra-draw.ts
Allows setting up custom properties on store objects with valid JSON values via the top level API method `updateFeatureProperty`.
https://github.com/JamesLMilner/terra-draw/issues/623
=> feat(terra-draw): allow setting of custom properties with updateFeatureProperties

guides/4.MODES.md
Adds `editable` documentation and also documentation for `pointerDistance`
https://github.com/JamesLMilner/terra-draw/issues/433
https://github.com/JamesLMilner/terra-draw/issues/642
=> docs(terra-draw): add editable and pointerDistance documentation

packages/terra-draw/src/terra-draw.ts
My first ever PR so bear with me
This adds option to allow getFeaturesAtPointerEvent() get snapping points out of the way ( #656 )
Didn't test, but should be fine as it is just few copypasted lines.
=> feat(terra-draw): provide a option for getFeaturesAt methods to ignore snapping points

packages/terra-draw/src/modes/angled-rectangle/angled-rectangle.mode.spec.ts, packages/terra-draw/src/modes/angled-rectangle/angled-rectangle.mode.ts
Precision wasn't being respected in TerraDrawAngledRectangleMode when we were calculating the onMouseMove coordinates
https://github.com/JamesLMilner/terra-draw/issues/659
=> fix(terra-draw): ensure precision is respected for TerraDrawAngledRectangleMode

.github/workflows/ci.yml, guides/7.DEVELOPMENT.md, package-lock.json, package.json, packages/terra-draw/package.json, packages/terra-draw/src/benchmark/setup.ts, packages/terra-draw/src/terra-draw.benchmark.ts, packages/terra-draw/src/test/test-adapter.ts
Adds basic benchmarking for the public API. This is adapter agnostic and just focuses on the Terra Draw API rather than rendering performance. The aim here is to be able to track performance regressions and also give some guidance on if performance is improved when actively trying to make operations faster.
https://github.com/JamesLMilner/terra-draw/issues/654
=> chore(terra-draw): add benchmarking for the public Terra Draw API
